from blocks import (DIRT, STONE, OBSIDIAN, TREE_LOG,
                    TUMBLER_BLOCK, CRUSHER_BLOCK, GEM_CUTTER_BLOCK,
                    KILN_BLOCK, RESONANCE_BLOCK, POLISHED_STONE_BLOCK,
                    LADDER, SUPPORT, IRON_SUPPORT, DIAMOND_SUPPORT, SAPLING,
                    WOOD_FENCE, IRON_FENCE, WOOD_DOOR_CLOSED, IRON_DOOR_CLOSED,
                    STRAWBERRY_CROP_YOUNG, WHEAT_CROP_YOUNG, BAKERY_BLOCK,
                    CARROT_CROP_YOUNG, TOMATO_CROP_YOUNG, CORN_CROP_YOUNG,
                    PUMPKIN_CROP_YOUNG, APPLE_CROP_YOUNG,
                    RICE_CROP_YOUNG, GINGER_CROP_YOUNG,
                    BOK_CHOY_CROP_YOUNG, GARLIC_CROP_YOUNG,
                    WOK_BLOCK, STEAMER_BLOCK, NOODLE_POT_BLOCK,
                    SCALLION_CROP_YOUNG, CHILI_CROP_YOUNG,
                    BBQ_GRILL_BLOCK, CLAY_POT_BLOCK,
                    PEPPER_CROP_YOUNG, ONION_CROP_YOUNG, POTATO_CROP_YOUNG,
                    EGGPLANT_CROP_YOUNG, CABBAGE_CROP_YOUNG, BED)

ITEMS = {
    # --- Natural resources ---
    "dirt_clump":    {"name": "Dirt Clump",    "color": (115, 77, 38),   "place_block": DIRT},
    "stone_chip":    {"name": "Stone Chip",    "color": (140, 140, 140), "place_block": STONE},
    "coal":          {"name": "Coal",          "color": (35, 35, 35),    "place_block": None},
    "iron_chunk":    {"name": "Iron Chunk",    "color": (185, 140, 110), "place_block": None},
    "gold_nugget":   {"name": "Gold Nugget",   "color": (218, 182, 55),  "place_block": None},
    "crystal_shard": {"name": "Crystal Shard", "color": (90, 220, 220),  "place_block": None},
    "ruby":          {"name": "Ruby",          "color": (210, 35, 35),   "place_block": None},
    "obsidian_slab": {"name": "Obsidian Slab", "color": (28, 14, 42),    "place_block": OBSIDIAN},
    "lumber":        {"name": "Lumber",        "color": (139, 90, 43),   "place_block": TREE_LOG},
    "sapling":       {"name": "Sapling",       "color": (60, 180, 60),   "place_block": SAPLING},
    # --- Raw ingredients (must be cooked before eating) ---
    "strawberry":      {"name": "Strawberry",      "color": (230, 40,  80),  "place_block": None},
    "wheat":           {"name": "Wheat",           "color": (230, 210, 60),  "place_block": None},
    "carrot":          {"name": "Carrot",          "color": (255, 140,  0),  "place_block": None},
    "tomato":          {"name": "Tomato",          "color": (210,  50, 50),  "place_block": None},
    "corn":            {"name": "Corn",            "color": (230, 210, 55),  "place_block": None},
    "pumpkin":         {"name": "Pumpkin",         "color": (200, 100, 30),  "place_block": None},
    "apple":           {"name": "Apple",           "color": (180,  40, 40),  "place_block": None},
    "egg":             {"name": "Egg",             "color": (245, 235, 200), "place_block": None},
    "mushroom":        {"name": "Mushroom",        "color": (175,  38,  38), "place_block": None},
    "rice":            {"name": "Rice",            "color": (220, 210, 150), "place_block": None},
    "ginger":          {"name": "Ginger",          "color": (200, 160,  60), "place_block": None},
    "bok_choy":        {"name": "Bok Choy",        "color": ( 50, 170,  80), "place_block": None},
    "garlic":          {"name": "Garlic",          "color": (230, 225, 200), "place_block": None},
    "scallion":        {"name": "Scallion",        "color": ( 60, 200,  80), "place_block": None},
    "chili":           {"name": "Chili",           "color": (215,  50,  40), "place_block": None},
    "pepper":          {"name": "Pepper",          "color": (215,  65,  30), "place_block": None},
    "onion":           {"name": "Onion",           "color": (175, 148,  85), "place_block": None},
    "potato":          {"name": "Potato",          "color": (160, 128,  62), "place_block": None},
    "eggplant":        {"name": "Eggplant",        "color": ( 95,  45, 135), "place_block": None},
    "cabbage":         {"name": "Cabbage",         "color": ( 75, 155,  85), "place_block": None},
    # --- Seeds ---
    "strawberry_seed": {"name": "Strawberry Seed", "color": (180, 60,  100), "place_block": STRAWBERRY_CROP_YOUNG},
    "wheat_seed":      {"name": "Wheat Seed",      "color": (200, 185, 70),  "place_block": WHEAT_CROP_YOUNG},
    "carrot_seed":     {"name": "Carrot Seed",     "color": (220, 120,  20), "place_block": CARROT_CROP_YOUNG},
    "tomato_seed":     {"name": "Tomato Seed",     "color": (190,  60,  60), "place_block": TOMATO_CROP_YOUNG},
    "corn_seed":       {"name": "Corn Seed",       "color": (200, 180,  50), "place_block": CORN_CROP_YOUNG},
    "pumpkin_seed":    {"name": "Pumpkin Seed",    "color": (180,  90,  20), "place_block": PUMPKIN_CROP_YOUNG},
    "apple_seed":      {"name": "Apple Seed",      "color": ( 60, 140,  60), "place_block": APPLE_CROP_YOUNG},
    "rice_seed":       {"name": "Rice Seed",       "color": (190, 180, 110), "place_block": RICE_CROP_YOUNG},
    "ginger_seed":     {"name": "Ginger Seed",     "color": (180, 140,  40), "place_block": GINGER_CROP_YOUNG},
    "bok_choy_seed":   {"name": "Bok Choy Seed",   "color": ( 40, 130,  60), "place_block": BOK_CHOY_CROP_YOUNG},
    "garlic_seed":     {"name": "Garlic Seed",     "color": (200, 195, 160), "place_block": GARLIC_CROP_YOUNG},
    "scallion_seed":   {"name": "Scallion Seed",   "color": ( 50, 155,  65), "place_block": SCALLION_CROP_YOUNG},
    "chili_seed":      {"name": "Chili Seed",      "color": (190,  60,  50), "place_block": CHILI_CROP_YOUNG},
    "pepper_seed":     {"name": "Pepper Seed",     "color": (195,  70,  35), "place_block": PEPPER_CROP_YOUNG},
    "onion_seed":      {"name": "Onion Seed",      "color": (160, 135,  75), "place_block": ONION_CROP_YOUNG},
    "potato_seed":     {"name": "Potato Seed",     "color": (145, 115,  55), "place_block": POTATO_CROP_YOUNG},
    "eggplant_seed":   {"name": "Eggplant Seed",   "color": ( 90,  45, 125), "place_block": EGGPLANT_CROP_YOUNG},
    "cabbage_seed":    {"name": "Cabbage Seed",    "color": ( 65, 140,  70), "place_block": CABBAGE_CROP_YOUNG},
    "stone_pickaxe": {"name": "Stone Pickaxe", "color": (155, 155, 168), "place_block": None, "pick_power": 1.5,  "max_uses": 20},
    "iron_pickaxe":  {"name": "Iron Pickaxe",  "color": (185, 150, 120), "place_block": None, "pick_power": 2.25, "max_uses": 60},
    "gold_pickaxe":  {"name": "Gold Pickaxe",  "color": (230, 195, 60),  "place_block": None, "pick_power": 3.0,  "max_uses": 100},
    "stone_axe":     {"name": "Stone Axe",     "color": (155, 155, 168), "place_block": None, "axe_power": 2.5,   "max_uses": 25},
    "iron_axe":      {"name": "Iron Axe",      "color": (185, 150, 120), "place_block": None, "axe_power": 4.0,   "max_uses": 70},
    "gold_axe":      {"name": "Gold Axe",      "color": (230, 195, 60),  "place_block": None, "axe_power": 6.0,   "max_uses": 120},
    "shears":        {"name": "Shears",        "color": (190, 190, 195), "place_block": None, "harvest_tool": True, "max_uses": 20},
    "bucket":        {"name": "Bucket",        "color": (160, 120, 60),  "place_block": None, "harvest_tool": True, "max_uses": 10},
    # --- Animal products ---
    "wool":          {"name": "Wool",          "color": (235, 235, 235), "place_block": None},
    "milk":          {"name": "Milk",          "color": (245, 245, 255), "place_block": None},
    # --- Refinery equipment (craftable + placeable) ---
    "tumbler_item":    {"name": "Rock Tumbler",      "color": (160, 120, 80),  "place_block": TUMBLER_BLOCK},
    "crusher_item":    {"name": "Stone Crusher",     "color": (100, 100, 100), "place_block": CRUSHER_BLOCK},
    "gem_cutter_item": {"name": "Gem Cutter",        "color": (80, 190, 190),  "place_block": GEM_CUTTER_BLOCK},
    "kiln_item":       {"name": "Alchemical Kiln",   "color": (200, 80, 40),   "place_block": KILN_BLOCK},
    "resonance_item":  {"name": "Resonance Chamber", "color": (100, 50, 200),  "place_block": RESONANCE_BLOCK},
    "bakery_item":     {"name": "Bakery",            "color": (180, 100, 50),  "place_block": BAKERY_BLOCK},
    "wok_item":        {"name": "Wok",              "color": ( 60,  50,  45), "place_block": WOK_BLOCK},
    "steamer_item":    {"name": "Steamer",          "color": (175, 150, 105), "place_block": STEAMER_BLOCK},
    "noodle_pot_item": {"name": "Noodle Pot",       "color": ( 85,  70,  55), "place_block": NOODLE_POT_BLOCK},
    "bbq_grill_item":  {"name": "BBQ Grill",        "color": ( 55,  45,  35), "place_block": BBQ_GRILL_BLOCK},
    "clay_pot_item":   {"name": "Clay Pot",         "color": (170, 100,  65), "place_block": CLAY_POT_BLOCK},
    # --- Baked goods ---
    "strawberry_jam":{"name": "Strawberry Jam","color": (210, 55, 90), "place_block": None, "edible": True, "hunger_restore": 45},
    "bread":        {"name": "Bread",        "color": (200, 150,  80), "place_block": None, "edible": True, "hunger_restore": 40},
    "cheese":       {"name": "Cheese",       "color": (240, 210,  80), "place_block": None, "edible": True, "hunger_restore": 30},
    "tomato_soup":  {"name": "Tomato Soup",  "color": (210,  60,  40), "place_block": None, "edible": True, "hunger_restore": 38},
    "corn_bread":   {"name": "Corn Bread",   "color": (215, 185,  80), "place_block": None, "edible": True, "hunger_restore": 42},
    "pumpkin_pie":  {"name": "Pumpkin Pie",  "color": (200, 110,  40), "place_block": None, "edible": True, "hunger_restore": 65},
    "apple_pie":    {"name": "Apple Pie",    "color": (190, 130,  60), "place_block": None, "edible": True, "hunger_restore": 60},
    "carrot_cake":  {"name": "Carrot Cake",  "color": (215, 160,  80), "place_block": None, "edible": True, "hunger_restore": 70},
    # --- Cooked foods (crafting table) ---
    "cooked_egg":   {"name": "Cooked Egg",   "color": (235, 210, 130), "place_block": None, "edible": True, "hunger_restore": 25},
    "omelette":     {"name": "Omelette",     "color": (230, 205, 100), "place_block": None, "edible": True, "hunger_restore": 45},
    "cheese_bread": {"name": "Cheese Bread", "color": (220, 175,  70), "place_block": None, "edible": True, "hunger_restore": 55},
    "noodles":      {"name": "Noodles",      "color": (230, 210, 140), "place_block": None, "edible": True, "hunger_restore": 20},
    "noodle_soup":  {"name": "Noodle Soup",  "color": (190, 150,  60), "place_block": None, "edible": True, "hunger_restore": 65},
    "sesame_noodles":   {"name": "Sesame Noodles",   "color": (210, 175,  80), "place_block": None, "edible": True, "hunger_restore": 52},
    "garlic_bok_choy":  {"name": "Garlic Bok Choy",  "color": ( 60, 160,  60), "place_block": None, "edible": True, "hunger_restore": 42},
    # --- Wok dishes ---
    "scallion_pancake": {"name": "Scallion Pancake", "color": (215, 175,  80), "place_block": None, "edible": True, "hunger_restore": 38},
    "chili_oil_tofu":   {"name": "Chili Oil Tofu",   "color": (220,  80,  40), "place_block": None, "edible": True, "hunger_restore": 70},
    "stir_fried_rice":  {"name": "Stir Fried Rice",  "color": (225, 195,  90), "place_block": None, "edible": True, "hunger_restore": 58},
    "spicy_corn":       {"name": "Spicy Corn",        "color": (220, 110,  30), "place_block": None, "edible": True, "hunger_restore": 40},
    "chili_bok_choy":   {"name": "Chili Bok Choy",   "color": ( 60, 150,  55), "place_block": None, "edible": True, "hunger_restore": 50},
    "scallion_eggs":    {"name": "Scallion Eggs",     "color": (235, 215, 110), "place_block": None, "edible": True, "hunger_restore": 48},
    # --- Steamer dishes ---
    "steamed_bun":      {"name": "Steamed Bun",       "color": (245, 235, 210), "place_block": None, "edible": True, "hunger_restore": 35},
    "lotus_rice":       {"name": "Lotus Rice",        "color": (235, 225, 175), "place_block": None, "edible": True, "hunger_restore": 62},
    "crystal_rolls":    {"name": "Crystal Rolls",     "color": (200, 230, 210), "place_block": None, "edible": True, "hunger_restore": 55},
    "steamed_egg":      {"name": "Steamed Egg",       "color": (240, 230, 180), "place_block": None, "edible": True, "hunger_restore": 45},
    "pumpkin_cake":     {"name": "Pumpkin Cake",      "color": (205, 125,  50), "place_block": None, "edible": True, "hunger_restore": 52},
    # --- Noodle Pot dishes ---
    "soy_sauce":        {"name": "Soy Sauce",         "color": ( 80,  40,  10), "place_block": None},
    "ramen":            {"name": "Ramen",              "color": (220, 175,  70), "place_block": None, "edible": True, "hunger_restore": 78},
    "chili_noodles":    {"name": "Chili Noodles",     "color": (210,  90,  45), "place_block": None, "edible": True, "hunger_restore": 68},
    "hot_pot_broth":    {"name": "Hot Pot Broth",     "color": (190,  70,  45), "place_block": None, "edible": True, "hunger_restore": 62},
    "scallion_soup":    {"name": "Scallion Soup",     "color": (150, 200, 130), "place_block": None, "edible": True, "hunger_restore": 50},
    # --- BBQ Grill dishes ---
    "grilled_corn":      {"name": "Grilled Corn",      "color": (235, 200,  60), "place_block": None, "edible": True, "hunger_restore": 32},
    "potato_wedges":     {"name": "Potato Wedges",     "color": (215, 175,  70), "place_block": None, "edible": True, "hunger_restore": 38},
    "bbq_eggplant":      {"name": "BBQ Eggplant",      "color": (110,  60, 150), "place_block": None, "edible": True, "hunger_restore": 48},
    "grilled_mushroom":  {"name": "Grilled Mushroom",  "color": (165,  90,  45), "place_block": None, "edible": True, "hunger_restore": 42},
    "stuffed_pepper":    {"name": "Stuffed Pepper",    "color": (210,  75,  40), "place_block": None, "edible": True, "hunger_restore": 65},
    "eggplant_skewer":   {"name": "Eggplant Skewer",   "color": (125,  65, 165), "place_block": None, "edible": True, "hunger_restore": 58},
    "corn_ribs":         {"name": "Corn Ribs",         "color": (225, 185,  50), "place_block": None, "edible": True, "hunger_restore": 52},
    "bbq_tofu":          {"name": "BBQ Tofu",          "color": (215, 155,  65), "place_block": None, "edible": True, "hunger_restore": 68},
    "roast_onion":       {"name": "Roast Onion",       "color": (195, 160,  90), "place_block": None, "edible": True, "hunger_restore": 30},
    "grilled_cabbage":   {"name": "Grilled Cabbage",   "color": ( 85, 155,  75), "place_block": None, "edible": True, "hunger_restore": 45},
    # --- Clay Pot dishes ---
    "potato_stew":       {"name": "Potato Stew",       "color": (175, 130,  60), "place_block": None, "edible": True, "hunger_restore": 55},
    "cabbage_soup":      {"name": "Cabbage Soup",      "color": (135, 185, 120), "place_block": None, "edible": True, "hunger_restore": 45},
    "braised_eggplant":  {"name": "Braised Eggplant",  "color": (105,  55, 145), "place_block": None, "edible": True, "hunger_restore": 62},
    "pepper_soup":       {"name": "Pepper Soup",       "color": (210,  85,  45), "place_block": None, "edible": True, "hunger_restore": 60},
    "onion_broth":       {"name": "Onion Broth",       "color": (210, 185, 120), "place_block": None, "edible": True, "hunger_restore": 40},
    "potato_mushroom_stew": {"name": "Potato Mushroom Stew", "color": (155, 110, 50), "place_block": None, "edible": True, "hunger_restore": 70},
    "stuffed_cabbage":   {"name": "Stuffed Cabbage",   "color": ( 90, 165,  90), "place_block": None, "edible": True, "hunger_restore": 65},
    "braised_tofu":      {"name": "Braised Tofu",      "color": (190, 155,  75), "place_block": None, "edible": True, "hunger_restore": 58},
    "pepper_pot":        {"name": "Pepper Pot",        "color": (200,  70,  40), "place_block": None, "edible": True, "hunger_restore": 55},
    "harvest_stew":      {"name": "Harvest Stew",      "color": (160, 110,  50), "place_block": None, "edible": True, "hunger_restore": 75},
    # --- Chinese cuisine (bakery) ---
    "tofu":          {"name": "Tofu",          "color": (240, 240, 225), "place_block": None, "edible": True, "hunger_restore": 25},
    "steamed_rice":  {"name": "Steamed Rice",  "color": (245, 245, 230), "place_block": None, "edible": True, "hunger_restore": 30},
    "egg_fried_rice":{"name": "Egg Fried Rice","color": (230, 210, 100), "place_block": None, "edible": True, "hunger_restore": 55},
    "congee":        {"name": "Congee",        "color": (235, 230, 210), "place_block": None, "edible": True, "hunger_restore": 45},
    "mapo_tofu":     {"name": "Mapo Tofu",     "color": (210,  60,  40), "place_block": None, "edible": True, "hunger_restore": 68},
    "dumplings":     {"name": "Dumplings",     "color": (230, 210, 170), "place_block": None, "edible": True, "hunger_restore": 65},
    "wonton_soup":   {"name": "Wonton Soup",   "color": (210, 170, 100), "place_block": None, "edible": True, "hunger_restore": 60},
    "kung_pao":      {"name": "Kung Pao",      "color": (210,  80,  40), "place_block": None, "edible": True, "hunger_restore": 72},
    "moon_cake":     {"name": "Moon Cake",     "color": (210, 155,  60), "place_block": None, "edible": True, "hunger_restore": 78},
    "hot_sour_soup": {"name": "Hot & Sour Soup","color":(195,  80,  50), "place_block": None, "edible": True, "hunger_restore": 58},
    "sweet_rice_ball":{"name": "Sweet Rice Ball","color":(240, 220, 190),"place_block": None, "edible": True, "hunger_restore": 55},
    # --- Refinery outputs ---
    "rock_dust":      {"name": "Rock Dust",      "color": (180, 160, 140), "place_block": None},
    "polished_stone": {"name": "Polished Stone", "color": (200, 200, 215), "place_block": POLISHED_STONE_BLOCK},
    "ladder_item":         {"name": "Ladder",          "color": (139, 90,  43),  "place_block": LADDER},
    "support_item":        {"name": "Support",         "color": (180, 140, 80),  "place_block": SUPPORT},
    "iron_support_item":   {"name": "Iron Support",    "color": (160, 170, 185), "place_block": IRON_SUPPORT},
    "diamond_support_item":{"name": "Diamond Support", "color": (100, 230, 220), "place_block": DIAMOND_SUPPORT},
    "diamond":             {"name": "Diamond",         "color": (180, 255, 255), "place_block": None},
    "quartz_gem":     {"name": "Quartz Gem",     "color": (230, 230, 255), "place_block": None},
    "amethyst_gem":   {"name": "Amethyst Gem",   "color": (160, 80, 200),  "place_block": None},
    "citrine_gem":    {"name": "Citrine Gem",    "color": (240, 180, 30),  "place_block": None},
    "fused_ingot":    {"name": "Fused Ingot",    "color": (100, 180, 160), "place_block": None},
    "void_essence":   {"name": "Void Essence",   "color": (80, 20, 120),   "place_block": None},
    # --- Fences and doors ---
    "wood_fence": {"name": "Wood Fence", "color": (139, 90,  43),  "place_block": WOOD_FENCE},
    "iron_fence": {"name": "Iron Fence", "color": (160, 160, 165), "place_block": IRON_FENCE},
    "wood_door":  {"name": "Wood Door",  "color": (139, 90,  43),  "place_block": WOOD_DOOR_CLOSED},
    "iron_door":  {"name": "Iron Door",  "color": (160, 160, 165), "place_block": IRON_DOOR_CLOSED},
    # --- Furniture ---
    "bed":                {"name": "Bed",            "color": (200, 80, 110),  "place_block": BED},
    # --- Automations ---
    "coal_miner_item":    {"name": "Coal Miner",    "color": (110, 90,  70),  "place_block": None, "spawn_automation": "coal_miner"},
    "iron_miner_item":    {"name": "Iron Miner",    "color": (160, 170, 180), "place_block": None, "spawn_automation": "iron_miner"},
    "crystal_miner_item": {"name": "Crystal Miner", "color": (80,  200, 220), "place_block": None, "spawn_automation": "crystal_miner"},
}
