from blocks import (DIRT, STONE, OBSIDIAN, TREE_LOG,
                    TUMBLER_BLOCK, CRUSHER_BLOCK, GEM_CUTTER_BLOCK,
                    KILN_BLOCK, RESONANCE_BLOCK, POLISHED_STONE_BLOCK,
                    LADDER, SAPLING,
                    WOOD_FENCE, IRON_FENCE, WOOD_DOOR_CLOSED, IRON_DOOR_CLOSED,
                    STRAWBERRY_CROP_YOUNG, WHEAT_CROP_YOUNG, BAKERY_BLOCK,
                    CARROT_CROP_YOUNG, TOMATO_CROP_YOUNG, CORN_CROP_YOUNG,
                    PUMPKIN_CROP_YOUNG, APPLE_CROP_YOUNG,
                    RICE_CROP_YOUNG, GINGER_CROP_YOUNG,
                    BOK_CHOY_CROP_YOUNG, GARLIC_CROP_YOUNG,
                    WOK_BLOCK, STEAMER_BLOCK, NOODLE_POT_BLOCK,
                    SCALLION_CROP_YOUNG, CHILI_CROP_YOUNG,
                    BBQ_GRILL_BLOCK, CLAY_POT_BLOCK,
                    PEPPER_CROP_YOUNG, ONION_CROP_YOUNG, POTATO_CROP_YOUNG,
                    EGGPLANT_CROP_YOUNG, CABBAGE_CROP_YOUNG, BED, CHEST_BLOCK,
                    BEET_CROP_YOUNG, TURNIP_CROP_YOUNG, LEEK_CROP_YOUNG,
                    ZUCCHINI_CROP_YOUNG, SWEET_POTATO_CROP_YOUNG, WATERMELON_CROP_YOUNG,
                    RADISH_CROP_YOUNG, PEA_CROP_YOUNG, CELERY_CROP_YOUNG, BROCCOLI_CROP_YOUNG,
                    CACTUS_YOUNG, SANDSTONE_BLOCK, DESERT_FORGE_BLOCK, SAND,
                    DATE_PALM_CROP_YOUNG, AGAVE_CROP_YOUNG,
                    BIRD_FEEDER_BLOCK, BIRD_BATH_BLOCK)

ITEMS = {
    # --- Natural resources ---
    "dirt_clump":    {"name": "Dirt Clump",    "color": (115, 77, 38),   "place_block": DIRT},
    "stone_chip":    {"name": "Stone Chip",    "color": (140, 140, 140), "place_block": STONE},
    "coal":          {"name": "Coal",          "color": (35, 35, 35),    "place_block": None},
    "iron_chunk":    {"name": "Iron Chunk",    "color": (185, 140, 110), "place_block": None},
    "gold_nugget":   {"name": "Gold Nugget",   "color": (218, 182, 55),  "place_block": None},
    "crystal_shard": {"name": "Crystal Shard", "color": (90, 220, 220),  "place_block": None},
    "ruby":          {"name": "Ruby",          "color": (210, 35, 35),   "place_block": None},
    "obsidian_slab": {"name": "Obsidian Slab", "color": (28, 14, 42),    "place_block": OBSIDIAN},
    "lumber":        {"name": "Lumber",        "color": (139, 90, 43),   "place_block": TREE_LOG},
    "sapling":       {"name": "Sapling",       "color": (60, 180, 60),   "place_block": SAPLING},
    # --- Raw ingredients (edible raw but at low nutrition) ---
    "strawberry":      {"name": "Strawberry",      "color": (230, 40,  80),  "place_block": None, "edible": True, "hunger_restore":  8},
    "wheat":           {"name": "Wheat",           "color": (230, 210, 60),  "place_block": None, "edible": True, "hunger_restore":  3},
    "carrot":          {"name": "Carrot",          "color": (255, 140,  0),  "place_block": None, "edible": True, "hunger_restore":  8},
    "tomato":          {"name": "Tomato",          "color": (210,  50, 50),  "place_block": None, "edible": True, "hunger_restore":  8},
    "corn":            {"name": "Corn",            "color": (230, 210, 55),  "place_block": None, "edible": True, "hunger_restore":  5},
    "pumpkin":         {"name": "Pumpkin",         "color": (200, 100, 30),  "place_block": None, "edible": True, "hunger_restore":  4},
    "apple":           {"name": "Apple",           "color": (180,  40, 40),  "place_block": None, "edible": True, "hunger_restore": 10},
    "egg":             {"name": "Egg",             "color": (245, 235, 200), "place_block": None, "edible": True, "hunger_restore":  4},
    "mushroom":        {"name": "Mushroom",        "color": (175,  38,  38), "place_block": None, "edible": True, "hunger_restore":  5},
    "rice":            {"name": "Rice",            "color": (220, 210, 150), "place_block": None, "edible": True, "hunger_restore":  3},
    "ginger":          {"name": "Ginger",          "color": (200, 160,  60), "place_block": None, "edible": True, "hunger_restore":  5},
    "bok_choy":        {"name": "Bok Choy",        "color": ( 50, 170,  80), "place_block": None, "edible": True, "hunger_restore":  7},
    "garlic":          {"name": "Garlic",          "color": (230, 225, 200), "place_block": None, "edible": True, "hunger_restore":  5},
    "scallion":        {"name": "Scallion",        "color": ( 60, 200,  80), "place_block": None, "edible": True, "hunger_restore":  6},
    "chili":           {"name": "Chili",           "color": (215,  50,  40), "place_block": None, "edible": True, "hunger_restore":  6},
    "pepper":          {"name": "Pepper",          "color": (215,  65,  30), "place_block": None, "edible": True, "hunger_restore": 15},
    "onion":           {"name": "Onion",           "color": (175, 148,  85), "place_block": None, "edible": True, "hunger_restore":  5},
    "potato":          {"name": "Potato",          "color": (160, 128,  62), "place_block": None, "edible": True, "hunger_restore":  3},
    "eggplant":        {"name": "Eggplant",        "color": ( 95,  45, 135), "place_block": None, "edible": True, "hunger_restore":  3},
    "cabbage":         {"name": "Cabbage",         "color": ( 75, 155,  85), "place_block": None, "edible": True, "hunger_restore":  6},
    "beet":            {"name": "Beet",            "color": (140,  30,  60), "place_block": None, "edible": True, "hunger_restore":  7},
    "turnip":          {"name": "Turnip",          "color": (210, 190, 215), "place_block": None, "edible": True, "hunger_restore":  5},
    "leek":            {"name": "Leek",            "color": ( 80, 195,  90), "place_block": None, "edible": True, "hunger_restore":  6},
    "zucchini":        {"name": "Zucchini",        "color": ( 70, 150,  55), "place_block": None, "edible": True, "hunger_restore":  5},
    "sweet_potato":    {"name": "Sweet Potato",    "color": (195, 100,  50), "place_block": None, "edible": True, "hunger_restore":  8},
    "watermelon":      {"name": "Watermelon",      "color": ( 55, 140,  50), "place_block": None, "edible": True, "hunger_restore": 12},
    "radish":          {"name": "Radish",          "color": (220,  60,  80), "place_block": None, "edible": True, "hunger_restore":  5},
    "pea":             {"name": "Pea",             "color": (100, 185,  70), "place_block": None, "edible": True, "hunger_restore":  6},
    "celery":          {"name": "Celery",          "color": ( 95, 185, 100), "place_block": None, "edible": True, "hunger_restore":  4},
    "broccoli":        {"name": "Broccoli",        "color": ( 45, 120,  55), "place_block": None, "edible": True, "hunger_restore":  7},
    # --- Desert ingredients ---
    "cactus_fruit":    {"name": "Cactus Fruit",    "color": ( 90, 195,  90), "place_block": None, "edible": True, "hunger_restore": 12},
    "date_palm_fruit": {"name": "Date",            "color": (165,  90,  30), "place_block": None, "edible": True, "hunger_restore": 15},
    "agave":           {"name": "Agave",           "color": ( 80, 165, 100), "place_block": None, "edible": True, "hunger_restore":  3},
    # --- Seeds ---
    "strawberry_seed": {"name": "Strawberry Seed", "color": (180, 60,  100), "place_block": STRAWBERRY_CROP_YOUNG},
    "wheat_seed":      {"name": "Wheat Seed",      "color": (200, 185, 70),  "place_block": WHEAT_CROP_YOUNG},
    "carrot_seed":     {"name": "Carrot Seed",     "color": (220, 120,  20), "place_block": CARROT_CROP_YOUNG},
    "tomato_seed":     {"name": "Tomato Seed",     "color": (190,  60,  60), "place_block": TOMATO_CROP_YOUNG},
    "corn_seed":       {"name": "Corn Seed",       "color": (200, 180,  50), "place_block": CORN_CROP_YOUNG},
    "pumpkin_seed":    {"name": "Pumpkin Seed",    "color": (180,  90,  20), "place_block": PUMPKIN_CROP_YOUNG},
    "apple_seed":      {"name": "Apple Seed",      "color": ( 60, 140,  60), "place_block": APPLE_CROP_YOUNG},
    "rice_seed":       {"name": "Rice Seed",       "color": (190, 180, 110), "place_block": RICE_CROP_YOUNG},
    "ginger_seed":     {"name": "Ginger Seed",     "color": (180, 140,  40), "place_block": GINGER_CROP_YOUNG},
    "bok_choy_seed":   {"name": "Bok Choy Seed",   "color": ( 40, 130,  60), "place_block": BOK_CHOY_CROP_YOUNG},
    "garlic_seed":     {"name": "Garlic Seed",     "color": (200, 195, 160), "place_block": GARLIC_CROP_YOUNG},
    "scallion_seed":   {"name": "Scallion Seed",   "color": ( 50, 155,  65), "place_block": SCALLION_CROP_YOUNG},
    "chili_seed":      {"name": "Chili Seed",      "color": (190,  60,  50), "place_block": CHILI_CROP_YOUNG},
    "pepper_seed":     {"name": "Pepper Seed",     "color": (195,  70,  35), "place_block": PEPPER_CROP_YOUNG},
    "onion_seed":      {"name": "Onion Seed",      "color": (160, 135,  75), "place_block": ONION_CROP_YOUNG},
    "potato_seed":     {"name": "Potato Seed",     "color": (145, 115,  55), "place_block": POTATO_CROP_YOUNG},
    "eggplant_seed":   {"name": "Eggplant Seed",   "color": ( 90,  45, 125), "place_block": EGGPLANT_CROP_YOUNG},
    "cabbage_seed":      {"name": "Cabbage Seed",      "color": ( 65, 140,  70),  "place_block": CABBAGE_CROP_YOUNG},
    "beet_seed":         {"name": "Beet Seed",         "color": (125,  30,  55),  "place_block": BEET_CROP_YOUNG},
    "turnip_seed":       {"name": "Turnip Seed",       "color": (185, 165, 190),  "place_block": TURNIP_CROP_YOUNG},
    "leek_seed":         {"name": "Leek Seed",         "color": ( 65, 160,  75),  "place_block": LEEK_CROP_YOUNG},
    "zucchini_seed":     {"name": "Zucchini Seed",     "color": ( 60, 130,  45),  "place_block": ZUCCHINI_CROP_YOUNG},
    "sweet_potato_seed": {"name": "Sweet Potato Seed", "color": (175,  85,  40),  "place_block": SWEET_POTATO_CROP_YOUNG},
    "watermelon_seed":   {"name": "Watermelon Seed",   "color": ( 45, 115,  40),  "place_block": WATERMELON_CROP_YOUNG},
    "radish_seed":       {"name": "Radish Seed",       "color": (195,  50,  70),  "place_block": RADISH_CROP_YOUNG},
    "pea_seed":          {"name": "Pea Seed",          "color": ( 85, 160,  60),  "place_block": PEA_CROP_YOUNG},
    "celery_seed":       {"name": "Celery Seed",       "color": ( 80, 160,  85),  "place_block": CELERY_CROP_YOUNG},
    "broccoli_seed":     {"name": "Broccoli Seed",     "color": ( 35,  95,  45),  "place_block": BROCCOLI_CROP_YOUNG},
    # --- Desert seeds / propagation items ---
    "cactus_spine":      {"name": "Cactus Spine",      "color": ( 50, 130,  50),  "place_block": CACTUS_YOUNG},
    "date_palm_seed":    {"name": "Date Palm Seed",    "color": (140,  80,  25),  "place_block": DATE_PALM_CROP_YOUNG},
    "agave_seed":        {"name": "Agave Seed",        "color": ( 60, 140,  80),  "place_block": AGAVE_CROP_YOUNG},
    "sand_grain":        {"name": "Sand",              "color": (210, 190, 140),  "place_block": SAND},
    "stone_pickaxe": {"name": "Stone Pickaxe", "color": (155, 155, 168), "place_block": None, "pick_power": 1.5,  "max_uses": 20},
    "iron_pickaxe":  {"name": "Iron Pickaxe",  "color": (185, 150, 120), "place_block": None, "pick_power": 2.25, "max_uses": 60},
    "gold_pickaxe":  {"name": "Gold Pickaxe",  "color": (230, 195, 60),  "place_block": None, "pick_power": 3.0,  "max_uses": 100},
    "stone_axe":     {"name": "Stone Axe",     "color": (155, 155, 168), "place_block": None, "axe_power": 2.5,   "max_uses": 25},
    "iron_axe":      {"name": "Iron Axe",      "color": (185, 150, 120), "place_block": None, "axe_power": 4.0,   "max_uses": 70},
    "gold_axe":      {"name": "Gold Axe",      "color": (230, 195, 60),  "place_block": None, "axe_power": 6.0,   "max_uses": 120},
    "shears":        {"name": "Shears",        "color": (190, 190, 195), "place_block": None, "harvest_tool": True, "max_uses": 20},
    "bucket":        {"name": "Bucket",        "color": (160, 120, 60),  "place_block": None, "harvest_tool": True, "max_uses": 10},
    # --- Animal products ---
    "wool":           {"name": "Wool",           "color": (235, 235, 235), "place_block": None},
    "milk":           {"name": "Milk",           "color": (245, 245, 255), "place_block": None},
    "raw_mutton":     {"name": "Raw Mutton",     "color": (210, 130, 110), "place_block": None, "edible": True, "hunger_restore":  6},
    "raw_beef":       {"name": "Raw Beef",       "color": (190,  90,  80), "place_block": None, "edible": True, "hunger_restore":  6},
    "raw_chicken":    {"name": "Raw Chicken",    "color": (225, 195, 155), "place_block": None, "edible": True, "hunger_restore":  6},
    "cooked_mutton":  {"name": "Cooked Mutton",  "color": (165,  80,  55), "place_block": None, "edible": True, "hunger_restore": 40},
    "cooked_beef":    {"name": "Cooked Beef",    "color": (145,  55,  35), "place_block": None, "edible": True, "hunger_restore": 40},
    "cooked_chicken": {"name": "Cooked Chicken", "color": (210, 170, 100), "place_block": None, "edible": True, "hunger_restore": 40},
    "hunting_knife":  {"name": "Hunting Knife",  "color": (170, 165, 160), "place_block": None, "harvest_tool": True, "max_uses": 15},
    # --- Refinery equipment (craftable + placeable) ---
    "tumbler_item":    {"name": "Rock Tumbler",      "color": (160, 120, 80),  "place_block": TUMBLER_BLOCK},
    "crusher_item":    {"name": "Stone Crusher",     "color": (100, 100, 100), "place_block": CRUSHER_BLOCK},
    "gem_cutter_item": {"name": "Gem Cutter",        "color": (80, 190, 190),  "place_block": GEM_CUTTER_BLOCK},
    "kiln_item":       {"name": "Alchemical Kiln",   "color": (200, 80, 40),   "place_block": KILN_BLOCK},
    "resonance_item":  {"name": "Resonance Chamber", "color": (100, 50, 200),  "place_block": RESONANCE_BLOCK},
    "bakery_item":     {"name": "Bakery",            "color": (180, 100, 50),  "place_block": BAKERY_BLOCK},
    "wok_item":        {"name": "Wok",              "color": ( 60,  50,  45), "place_block": WOK_BLOCK},
    "steamer_item":    {"name": "Steamer",          "color": (175, 150, 105), "place_block": STEAMER_BLOCK},
    "noodle_pot_item": {"name": "Noodle Pot",       "color": ( 85,  70,  55), "place_block": NOODLE_POT_BLOCK},
    "bbq_grill_item":  {"name": "BBQ Grill",        "color": ( 55,  45,  35), "place_block": BBQ_GRILL_BLOCK},
    "clay_pot_item":   {"name": "Clay Pot",         "color": (170, 100,  65), "place_block": CLAY_POT_BLOCK},
    "desert_forge_item":{"name": "Desert Forge",   "color": (175,  95,  40), "place_block": DESERT_FORGE_BLOCK},
    # --- Desert forge outputs ---
    "sandstone":       {"name": "Sandstone",        "color": (210, 185, 120), "place_block": SANDSTONE_BLOCK},
    "desert_glass":    {"name": "Desert Glass",     "color": (190, 215, 190), "place_block": None},
    "tempered_iron":   {"name": "Tempered Iron",    "color": (150, 165, 180), "place_block": None},
    "cactus_fiber":    {"name": "Cactus Fiber",     "color": ( 90, 160,  75), "place_block": None},
    "agave_syrup":     {"name": "Agave Syrup",      "color": (195, 150,  45), "place_block": None},
    # --- Tempered tools ---
    "tempered_pickaxe":{"name": "Tempered Pickaxe","color": (150, 165, 180), "place_block": None, "pick_power": 3.5, "max_uses": 150},
    "tempered_axe":    {"name": "Tempered Axe",    "color": (150, 165, 180), "place_block": None, "axe_power":  7.0, "max_uses": 160},
    # --- Baked goods ---
    "strawberry_jam":{"name": "Strawberry Jam","color": (210, 55, 90), "place_block": None, "edible": True, "hunger_restore": 45},
    "bread":        {"name": "Bread",        "color": (200, 150,  80), "place_block": None, "edible": True, "hunger_restore": 40},
    "cheese":       {"name": "Cheese",       "color": (240, 210,  80), "place_block": None, "edible": True, "hunger_restore": 30},
    "tomato_soup":  {"name": "Tomato Soup",  "color": (210,  60,  40), "place_block": None, "edible": True, "hunger_restore": 38},
    "corn_bread":   {"name": "Corn Bread",   "color": (215, 185,  80), "place_block": None, "edible": True, "hunger_restore": 42},
    "pumpkin_pie":  {"name": "Pumpkin Pie",  "color": (200, 110,  40), "place_block": None, "edible": True, "hunger_restore": 65},
    "apple_pie":    {"name": "Apple Pie",    "color": (190, 130,  60), "place_block": None, "edible": True, "hunger_restore": 60},
    "carrot_cake":  {"name": "Carrot Cake",  "color": (215, 160,  80), "place_block": None, "edible": True, "hunger_restore": 70},
    # --- Cooked foods (crafting table) ---
    "cooked_egg":   {"name": "Cooked Egg",   "color": (235, 210, 130), "place_block": None, "edible": True, "hunger_restore": 25},
    "omelette":     {"name": "Omelette",     "color": (230, 205, 100), "place_block": None, "edible": True, "hunger_restore": 45},
    "cheese_bread": {"name": "Cheese Bread", "color": (220, 175,  70), "place_block": None, "edible": True, "hunger_restore": 55},
    "noodles":      {"name": "Noodles",      "color": (230, 210, 140), "place_block": None, "edible": True, "hunger_restore": 20},
    "noodle_soup":  {"name": "Noodle Soup",  "color": (190, 150,  60), "place_block": None, "edible": True, "hunger_restore": 65},
    "sesame_noodles":   {"name": "Sesame Noodles",   "color": (210, 175,  80), "place_block": None, "edible": True, "hunger_restore": 52},
    "garlic_bok_choy":  {"name": "Garlic Bok Choy",  "color": ( 60, 160,  60), "place_block": None, "edible": True, "hunger_restore": 42},
    # --- Wok dishes ---
    "scallion_pancake": {"name": "Scallion Pancake", "color": (215, 175,  80), "place_block": None, "edible": True, "hunger_restore": 38},
    "chili_oil_tofu":   {"name": "Chili Oil Tofu",   "color": (220,  80,  40), "place_block": None, "edible": True, "hunger_restore": 70},
    "stir_fried_rice":  {"name": "Stir Fried Rice",  "color": (225, 195,  90), "place_block": None, "edible": True, "hunger_restore": 58},
    "spicy_corn":       {"name": "Spicy Corn",        "color": (220, 110,  30), "place_block": None, "edible": True, "hunger_restore": 40},
    "chili_bok_choy":   {"name": "Chili Bok Choy",   "color": ( 60, 150,  55), "place_block": None, "edible": True, "hunger_restore": 50},
    "scallion_eggs":    {"name": "Scallion Eggs",     "color": (235, 215, 110), "place_block": None, "edible": True, "hunger_restore": 48},
    # --- Steamer dishes ---
    "steamed_bun":      {"name": "Steamed Bun",       "color": (245, 235, 210), "place_block": None, "edible": True, "hunger_restore": 35},
    "lotus_rice":       {"name": "Lotus Rice",        "color": (235, 225, 175), "place_block": None, "edible": True, "hunger_restore": 62},
    "crystal_rolls":    {"name": "Crystal Rolls",     "color": (200, 230, 210), "place_block": None, "edible": True, "hunger_restore": 55},
    "steamed_egg":      {"name": "Steamed Egg",       "color": (240, 230, 180), "place_block": None, "edible": True, "hunger_restore": 45},
    "pumpkin_cake":     {"name": "Pumpkin Cake",      "color": (205, 125,  50), "place_block": None, "edible": True, "hunger_restore": 52},
    # --- Noodle Pot dishes ---
    "soy_sauce":        {"name": "Soy Sauce",         "color": ( 80,  40,  10), "place_block": None},
    "ramen":            {"name": "Ramen",              "color": (220, 175,  70), "place_block": None, "edible": True, "hunger_restore": 78},
    "chili_noodles":    {"name": "Chili Noodles",     "color": (210,  90,  45), "place_block": None, "edible": True, "hunger_restore": 68},
    "hot_pot_broth":    {"name": "Hot Pot Broth",     "color": (190,  70,  45), "place_block": None, "edible": True, "hunger_restore": 62},
    "scallion_soup":    {"name": "Scallion Soup",     "color": (150, 200, 130), "place_block": None, "edible": True, "hunger_restore": 50},
    # --- BBQ Grill dishes ---
    "grilled_corn":      {"name": "Grilled Corn",      "color": (235, 200,  60), "place_block": None, "edible": True, "hunger_restore": 32},
    "potato_wedges":     {"name": "Potato Wedges",     "color": (215, 175,  70), "place_block": None, "edible": True, "hunger_restore": 38},
    "bbq_eggplant":      {"name": "BBQ Eggplant",      "color": (110,  60, 150), "place_block": None, "edible": True, "hunger_restore": 48},
    "grilled_mushroom":  {"name": "Grilled Mushroom",  "color": (165,  90,  45), "place_block": None, "edible": True, "hunger_restore": 42},
    "stuffed_pepper":    {"name": "Stuffed Pepper",    "color": (210,  75,  40), "place_block": None, "edible": True, "hunger_restore": 65},
    "eggplant_skewer":   {"name": "Eggplant Skewer",   "color": (125,  65, 165), "place_block": None, "edible": True, "hunger_restore": 58},
    "corn_ribs":         {"name": "Corn Ribs",         "color": (225, 185,  50), "place_block": None, "edible": True, "hunger_restore": 52},
    "bbq_tofu":          {"name": "BBQ Tofu",          "color": (215, 155,  65), "place_block": None, "edible": True, "hunger_restore": 68},
    "roast_onion":       {"name": "Roast Onion",       "color": (195, 160,  90), "place_block": None, "edible": True, "hunger_restore": 30},
    "grilled_cabbage":   {"name": "Grilled Cabbage",   "color": ( 85, 155,  75), "place_block": None, "edible": True, "hunger_restore": 45},
    # --- Clay Pot dishes ---
    "potato_stew":       {"name": "Potato Stew",       "color": (175, 130,  60), "place_block": None, "edible": True, "hunger_restore": 55},
    "cabbage_soup":      {"name": "Cabbage Soup",      "color": (135, 185, 120), "place_block": None, "edible": True, "hunger_restore": 45},
    "braised_eggplant":  {"name": "Braised Eggplant",  "color": (105,  55, 145), "place_block": None, "edible": True, "hunger_restore": 62},
    "pepper_soup":       {"name": "Pepper Soup",       "color": (210,  85,  45), "place_block": None, "edible": True, "hunger_restore": 60},
    "onion_broth":       {"name": "Onion Broth",       "color": (210, 185, 120), "place_block": None, "edible": True, "hunger_restore": 40},
    "potato_mushroom_stew": {"name": "Potato Mushroom Stew", "color": (155, 110, 50), "place_block": None, "edible": True, "hunger_restore": 70},
    "stuffed_cabbage":   {"name": "Stuffed Cabbage",   "color": ( 90, 165,  90), "place_block": None, "edible": True, "hunger_restore": 65},
    "braised_tofu":      {"name": "Braised Tofu",      "color": (190, 155,  75), "place_block": None, "edible": True, "hunger_restore": 58},
    "pepper_pot":        {"name": "Pepper Pot",        "color": (200,  70,  40), "place_block": None, "edible": True, "hunger_restore": 55},
    "harvest_stew":      {"name": "Harvest Stew",      "color": (160, 110,  50), "place_block": None, "edible": True, "hunger_restore": 75},
    "beet_soup":         {"name": "Beet Soup",         "color": (155,  35,  65), "place_block": None, "edible": True, "hunger_restore": 45},
    "root_medley":       {"name": "Root Medley",       "color": (160,  75,  55), "place_block": None, "edible": True, "hunger_restore": 65},
    "radish_kimchi":     {"name": "Radish Kimchi",     "color": (210,  60,  70), "place_block": None, "edible": True, "hunger_restore": 42},
    "pea_soup":          {"name": "Pea Soup",          "color": (120, 185,  90), "place_block": None, "edible": True, "hunger_restore": 48},
    "stuffed_zucchini":  {"name": "Stuffed Zucchini",  "color": ( 70, 145,  55), "place_block": None, "edible": True, "hunger_restore": 60},
    "garden_soup":       {"name": "Garden Soup",       "color": ( 90, 175,  85), "place_block": None, "edible": True, "hunger_restore": 65},
    "turnip_mash":       {"name": "Turnip Mash",       "color": (215, 195, 210), "place_block": None, "edible": True, "hunger_restore": 35},
    "zucchini_stir_fry": {"name": "Zucchini Stir Fry", "color": ( 75, 155,  60), "place_block": None, "edible": True, "hunger_restore": 50},
    "celery_stir_fry":   {"name": "Celery Stir Fry",   "color": (100, 190, 105), "place_block": None, "edible": True, "hunger_restore": 42},
    "broccoli_stir_fry": {"name": "Broccoli Stir Fry", "color": ( 50, 125,  55), "place_block": None, "edible": True, "hunger_restore": 50},
    "leek_potato_soup":  {"name": "Leek & Potato Soup","color": (190, 175, 115), "place_block": None, "edible": True, "hunger_restore": 55},
    "sweet_potato_pie":  {"name": "Sweet Potato Pie",  "color": (200, 105,  50), "place_block": None, "edible": True, "hunger_restore": 65},
    "sweet_potato_wedges":{"name": "Sweet Potato Wedges","color":(205, 115,  55),"place_block": None, "edible": True, "hunger_restore": 45},
    "grilled_leek":      {"name": "Grilled Leek",      "color": ( 85, 175,  80), "place_block": None, "edible": True, "hunger_restore": 40},
    "watermelon_salad":  {"name": "Watermelon Salad",  "color": ( 65, 155,  60), "place_block": None, "edible": True, "hunger_restore": 38},
    # --- Desert food ---
    "grilled_cactus":    {"name": "Grilled Cactus",    "color": ( 75, 165,  65), "place_block": None, "edible": True, "hunger_restore": 28},
    "date_cake":         {"name": "Date Cake",         "color": (190, 130,  55), "place_block": None, "edible": True, "hunger_restore": 70},
    "cactus_candy":      {"name": "Cactus Candy",      "color": (115, 205, 115), "place_block": None, "edible": True, "hunger_restore": 55},
    "desert_salad":      {"name": "Desert Salad",      "color": ( 80, 180,  80), "place_block": None, "edible": True, "hunger_restore": 38},
    "date_palm_broth":   {"name": "Date Palm Broth",   "color": (185, 140,  65), "place_block": None, "edible": True, "hunger_restore": 52},
    # --- Chinese cuisine (bakery) ---
    "tofu":          {"name": "Tofu",          "color": (240, 240, 225), "place_block": None, "edible": True, "hunger_restore": 25},
    "steamed_rice":  {"name": "Steamed Rice",  "color": (245, 245, 230), "place_block": None, "edible": True, "hunger_restore": 30},
    "egg_fried_rice":{"name": "Egg Fried Rice","color": (230, 210, 100), "place_block": None, "edible": True, "hunger_restore": 55},
    "congee":        {"name": "Congee",        "color": (235, 230, 210), "place_block": None, "edible": True, "hunger_restore": 45},
    "mapo_tofu":     {"name": "Mapo Tofu",     "color": (210,  60,  40), "place_block": None, "edible": True, "hunger_restore": 68},
    "dumplings":     {"name": "Dumplings",     "color": (230, 210, 170), "place_block": None, "edible": True, "hunger_restore": 65},
    "wonton_soup":   {"name": "Wonton Soup",   "color": (210, 170, 100), "place_block": None, "edible": True, "hunger_restore": 60},
    "kung_pao":      {"name": "Kung Pao",      "color": (210,  80,  40), "place_block": None, "edible": True, "hunger_restore": 72},
    "moon_cake":     {"name": "Moon Cake",     "color": (210, 155,  60), "place_block": None, "edible": True, "hunger_restore": 78},
    "hot_sour_soup": {"name": "Hot & Sour Soup","color":(195,  80,  50), "place_block": None, "edible": True, "hunger_restore": 58},
    "sweet_rice_ball":{"name": "Sweet Rice Ball","color":(240, 220, 190),"place_block": None, "edible": True, "hunger_restore": 55},
    # --- Refinery outputs ---
    "rock_dust":      {"name": "Rock Dust",      "color": (180, 160, 140), "place_block": None},
    "polished_stone": {"name": "Polished Stone", "color": (200, 200, 215), "place_block": POLISHED_STONE_BLOCK},
    "ladder_item":         {"name": "Ladder",          "color": (139, 90,  43),  "place_block": LADDER},
    "diamond":             {"name": "Diamond",         "color": (180, 255, 255), "place_block": None},
    "quartz_gem":     {"name": "Quartz Gem",     "color": (230, 230, 255), "place_block": None},
    "amethyst_gem":   {"name": "Amethyst Gem",   "color": (160, 80, 200),  "place_block": None},
    "citrine_gem":    {"name": "Citrine Gem",    "color": (240, 180, 30),  "place_block": None},
    "fused_ingot":    {"name": "Fused Ingot",    "color": (100, 180, 160), "place_block": None},
    "void_essence":   {"name": "Void Essence",   "color": (80, 20, 120),   "place_block": None},
    # --- Fences and doors ---
    "wood_fence": {"name": "Wood Fence", "color": (139, 90,  43),  "place_block": WOOD_FENCE},
    "iron_fence": {"name": "Iron Fence", "color": (160, 160, 165), "place_block": IRON_FENCE},
    "wood_door":  {"name": "Wood Door",  "color": (139, 90,  43),  "place_block": WOOD_DOOR_CLOSED},
    "iron_door":  {"name": "Iron Door",  "color": (160, 160, 165), "place_block": IRON_DOOR_CLOSED},
    # --- Furniture ---
    "bed":                {"name": "Bed",            "color": (200, 80, 110),  "place_block": BED},
    "chest_item":         {"name": "Chest",          "color": (160, 110, 55),  "place_block": CHEST_BLOCK},
    "bird_feeder":        {"name": "Bird Feeder",    "color": (160, 115,  65), "place_block": BIRD_FEEDER_BLOCK},
    "bird_bath":          {"name": "Bird Bath",      "color": (185, 180, 172), "place_block": BIRD_BATH_BLOCK},
    # --- Automations ---
    "coal_miner_item":    {"name": "Coal Miner",    "color": (110, 90,  70),  "place_block": None, "spawn_automation": "coal_miner"},
    "iron_miner_item":    {"name": "Iron Miner",    "color": (160, 170, 180), "place_block": None, "spawn_automation": "iron_miner"},
    "crystal_miner_item": {"name": "Crystal Miner", "color": (80,  200, 220), "place_block": None, "spawn_automation": "crystal_miner"},
    # --- Farm Bots ---
    "farm_bot_item":         {"name": "Farm Bot",         "color": (80,  160, 60),  "place_block": None, "spawn_automation": "farm_bot"},
    "iron_farm_bot_item":    {"name": "Iron Farm Bot",    "color": (160, 180, 160), "place_block": None, "spawn_automation": "iron_farm_bot"},
    "crystal_farm_bot_item": {"name": "Crystal Farm Bot", "color": (100, 220, 200), "place_block": None, "spawn_automation": "crystal_farm_bot"},
    # --- Construction Equipment ---
    "empty_barrel": {"name": "Empty Barrel", "color": (110, 80,  45),  "place_block": None, "harvest_oil": True},
    "oil_barrel":   {"name": "Oil Barrel",   "color": ( 30, 25,  15),  "place_block": None},
    "backhoe_item": {"name": "Backhoe",      "color": (210, 160, 30),  "place_block": None, "spawn_backhoe": True},
    # --- Fishing ---
    "fishing_pole": {"name": "Fishing Pole", "color": (139, 90,  43),  "place_block": None, "fishing_tool": True, "max_uses": 60},
    "fish":         {"name": "Fish",         "color": (100, 160, 200), "place_block": None, "edible": True, "hunger_restore": 30},
}
