import pygame
from constants import SCREEN_W, SCREEN_H

_TOPICS = [
    "Distilling",
    "Wine Making",
    "Coffee Making",
    "Tea Making",
    "Herbalism",
    "Textile Arts",
    "Farming",
    "Horse Taming",
    "Animal Taming",
    "Crafting",
    "Mining",
    "Collecting",
    "Research",
    "Sculpting",
    "Pottery",
    "Salt",
]

_CONTENT = {
    "Distilling": [
        ("header",  "Distilling Spirits"),
        ("body",    "Each biome grows a different grain that produces a unique"),
        ("body",    "spirit type. Harvest mature grain plants to collect raw mash,"),
        ("body",    "then process it through three stations."),
        ("gap",),
        ("section", "STEP 1 — Grow & Harvest"),
        ("body",    "Plant grain seeds in a biome. Each biome yields a"),
        ("body",    "different grain and spirit variety:"),
        ("bullet",  "Tropical / Beach          →  Sugarcane  →  Rum"),
        ("bullet",  "Jungle / Savanna          →  Corn       →  Bourbon"),
        ("bullet",  "Wetland / Swamp           →  Botanical  →  Gin"),
        ("bullet",  "Alpine / Rocky Mountain   →  Pomace     →  Brandy"),
        ("bullet",  "Tundra / Boreal           →  Grain      →  Vodka"),
        ("bullet",  "Arid Steppe / Canyon / Rolling Hills  →  Grain  →  Whiskey"),
        ("body",    "Harvest fully-grown plants to receive raw mash items."),
        ("gap",),
        ("section", "STEP 2 — Copper Still  (Distillation)"),
        ("body",    "Place a Copper Still block and press E nearby to open it."),
        ("body",    "Select a raw mash from your inventory to load the still."),
        ("gap",),
        ("body",    "Mini-game: Hold SPACE to heat the still. Watch the"),
        ("body",    "temperature gauge rise. When the needle reaches the"),
        ("body",    "green zone, release SPACE to make the 'hearts cut'."),
        ("body",    "You must make 2 cuts total. Cutting inside the green"),
        ("body",    "zone raises cut quality and proof; cutting outside"),
        ("body",    "lowers them. Timing both cuts well gives the best result."),
        ("gap",),
        ("section", "STEP 3 — Barrel Room  (Aging)"),
        ("body",    "Place a Barrel Room block and press E to open it."),
        ("body",    "Select a distilled spirit, choose a barrel type and"),
        ("body",    "a maturation duration, then confirm to begin aging."),
        ("gap",),
        ("body",    "Barrel types shape the flavor notes:"),
        ("bullet",  "New Oak      — bold tannins, sawdust, fresh wood"),
        ("bullet",  "Charred Oak  — vanilla, caramel, sweet smoke"),
        ("bullet",  "Used Oak     — gentle oak, dried fruit, soft finish"),
        ("gap",),
        ("body",    "Duration options: Short, Medium, or Long."),
        ("body",    "Longer aging improves age quality but takes more time."),
        ("gap",),
        ("section", "STEP 4 — Bottling Station  (Bottle or Blend)"),
        ("body",    "Place a Bottling Station block and press E to open it."),
        ("body",    "Bottle a single aged spirit to add it to your collection,"),
        ("body",    "or blend up to 3 spirits together. A blend averages the"),
        ("body",    "attributes of all components and combines their flavor"),
        ("body",    "notes into a unique spirit of its own."),
        ("gap",),
        ("section", "QUALITY"),
        ("body",    "A spirit's final quality is determined by:"),
        ("bullet",  "Cut quality  — precision of the hearts cut in the Still"),
        ("bullet",  "Proof        — alcohol content (higher cut = higher proof)"),
        ("bullet",  "Age quality  — set by barrel type and duration"),
        ("bullet",  "Smoothness   — base attribute from the grain's biome"),
    ],
    "Wine Making": [
        ("header",  "Wine Making"),
        ("body",    "Each biome grows a grape variety with its own flavor profile."),
        ("body",    "Harvest mature grape vines to collect raw clusters, then"),
        ("body",    "process them through three stations."),
        ("gap",),
        ("section", "BIOME → GRAPE VARIETY"),
        ("bullet",  "Tropical           →  Sauvignon Blanc"),
        ("bullet",  "Jungle             →  Syrah"),
        ("bullet",  "Savanna            →  Tempranillo"),
        ("bullet",  "Wetland            →  Pinot Noir"),
        ("bullet",  "Arid Steppe        →  Grenache"),
        ("bullet",  "Canyon             →  Cabernet Sauvignon"),
        ("bullet",  "Beach              →  Riesling"),
        ("bullet",  "Tundra             →  Pinot Gris"),
        ("bullet",  "Swamp              →  Malbec"),
        ("bullet",  "Alpine Mountain    →  Chardonnay"),
        ("bullet",  "Rocky Mountain     →  Nebbiolo"),
        ("bullet",  "Rolling Hills      →  Merlot"),
        ("gap",),
        ("section", "STEP 1 — Grape Press  (Crush)"),
        ("body",    "Place a Grape Press block and press E to open it."),
        ("body",    "Select raw grapes, then choose a crush style:"),
        ("bullet",  "Whole Cluster    — stems in; adds tannin and earthiness"),
        ("bullet",  "Destemmed        — classic, balanced fruit"),
        ("bullet",  "Rosé Bleed       — brief skin contact; light, bright rosé"),
        ("bullet",  "Skin Fermented   — long skin contact; amber, textured"),
        ("gap",),
        ("body",    "Mini-game: Hold SPACE (or click PRESS) to build pressure."),
        ("body",    "Keep the gauge in the green zone as long as possible."),
        ("body",    "Two milestones fire automatically — Free-Run (~10 s) and"),
        ("body",    "Press-Wine (~22 s). Press ENTER or click STOP when done."),
        ("body",    "Over-pressing penalises quality; under-pressing wastes yield."),
        ("gap",),
        ("section", "STEP 2 — Fermentation Tank"),
        ("body",    "Place a Fermentation Tank block and press E to open it."),
        ("body",    "Select crushed grapes, then choose a yeast strain:"),
        ("bullet",  "Wild       — high complexity, lower alcohol, unpredictable"),
        ("bullet",  "Champagne  — clean, high-alcohol, biased to sparkling"),
        ("bullet",  "Bordeaux   — structured; builds body and tannin"),
        ("bullet",  "Burgundy   — elegant; aromatic lift, moderate body"),
        ("gap",),
        ("body",    "Mini-game: Hold SPACE to raise temperature, press N to add"),
        ("body",    "nutrients. Keep both in their target bands. Stop fermentation"),
        ("body",    "early for sweeter, lower-alcohol wine; let it run for drier,"),
        ("body",    "higher-alcohol results."),
        ("gap",),
        ("section", "STEP 3 — Wine Cellar  (Age, Blend & Bottle)"),
        ("body",    "Place a Wine Cellar block and press E to open it."),
        ("body",    "Three tabs are available:"),
        ("gap",),
        ("body",    "Age tab — select a fermented wine, choose a vessel:"),
        ("bullet",  "Oak Barrel   — adds body, spice, complexity"),
        ("bullet",  "Steel Tank   — preserves brightness and fruit"),
        ("bullet",  "Clay Amphora — earthy, mineral, gentle oxidation"),
        ("body",    "Then choose duration: Short (6 mo), Medium (2 yr), Long (5 yr)."),
        ("body",    "Longer aging adds complexity and quality."),
        ("gap",),
        ("body",    "Blend tab — combine up to 3 aged wines into one blend."),
        ("gap",),
        ("body",    "Bottle tab — choose serving temperature and glass style."),
        ("body",    "Serving temperature affects buff duration and quality:"),
        ("bullet",  "Chilled    — longer buff duration, small quality bonus"),
        ("bullet",  "Cellar     — balanced duration, best quality bonus"),
        ("bullet",  "Room Temp  — shorter duration, minimal bonus"),
        ("gap",),
        ("section", "WINE STYLES & BUFFS"),
        ("bullet",  "Red Wine     — warmth buff  (cold damage -50%)"),
        ("bullet",  "White Wine   — serenity buff  (hunger drain -60%)"),
        ("bullet",  "Rosé         — charm buff  (collect radius +75%)"),
        ("bullet",  "Sparkling    — vivacity buff  (jump +1, no fall damage)"),
        ("bullet",  "Dessert Wine — contemplation buff  (XP +25%)"),
    ],
    "Coffee Making": [
        ("header",  "Coffee Making"),
        ("body",    "Each biome grows a coffee variety with distinct flavor attributes."),
        ("body",    "Harvest mature coffee cherry plants to collect raw beans, then"),
        ("body",    "process them through the Roaster and Blend Station."),
        ("gap",),
        ("section", "BIOME → VARIETY"),
        ("bullet",  "Tropical / Beach / Alpine / Tundra / Rolling Hills  →  Arabica"),
        ("bullet",  "Savanna / Wetland / Swamp / Boreal                  →  Robusta"),
        ("bullet",  "Arid Steppe / Canyon / Rocky Mountain               →  Liberica"),
        ("gap",),
        ("section", "STEP 1 — Choose a Processing Method"),
        ("body",    "When opening raw beans in the Roaster, select a processing"),
        ("body",    "method before roasting. This shapes the base flavor:"),
        ("bullet",  "Washed   — clean, bright, acidity-forward; tea-like clarity"),
        ("bullet",  "Natural  — fruity, fermented, heavy sweetness"),
        ("bullet",  "Honey    — sweet and complex; apricot and nectarine notes"),
        ("gap",),
        ("section", "STEP 2 — Roaster  (Roasting Mini-game)"),
        ("body",    "Place a Roaster block and press E to open it."),
        ("body",    "Select a raw bean, choose processing, then begin the roast."),
        ("gap",),
        ("body",    "Mini-game: Hold SPACE to apply heat. Watch the temperature"),
        ("body",    "gauge. Roast level is determined by how long the bean stays"),
        ("body",    "in each temperature zone:"),
        ("bullet",  "Light   — bright, delicate, tea-like (stop early)"),
        ("bullet",  "Medium  — balanced, caramel, full flavour (hit first crack)"),
        ("bullet",  "Dark    — bold, smoky, low acidity (push past second crack)"),
        ("bullet",  "Charred — burnt and bitter (over-roasted)"),
        ("gap",),
        ("body",    "Hit First Crack for best quality; hold for Second Crack for"),
        ("body",    "dark roast. Release heat and stop to lock in your roast level."),
        ("gap",),
        ("section", "STEP 3 — Blend Station  (Optional)"),
        ("body",    "Place a Blend Station block and press E to open it."),
        ("body",    "Combine up to 3 roasted beans into a single blend. The blend"),
        ("body",    "averages the flavor attributes and combines flavor notes."),
        ("gap",),
        ("section", "STEP 4 — Brewing  (Brew Station)"),
        ("body",    "Place a Brew Station block and press E to open it."),
        ("body",    "Choose a brew method, grind size, and water quality:"),
        ("gap",),
        ("body",    "Brew methods:"),
        ("bullet",  "Drip         — focus buff  (amplifies sweetness & brightness)"),
        ("bullet",  "Espresso     — rush buff  (amplifies body & acidity)"),
        ("bullet",  "Pour Over    — clarity buff  (amplifies acidity & brightness)"),
        ("bullet",  "Cold Brew    — endurance buff  (amplifies sweetness & body)"),
        ("bullet",  "French Press — strength buff  (amplifies body & earthiness)"),
        ("gap",),
        ("body",    "Grind size affects extraction:"),
        ("bullet",  "Coarse  — longer, softer, smoother"),
        ("bullet",  "Medium  — balanced"),
        ("bullet",  "Fine    — fast, concentrated, bold"),
        ("gap",),
        ("body",    "Water quality:"),
        ("bullet",  "Soft     — highlights acidity and brightness"),
        ("bullet",  "Hard     — boosts body, mutes brightness"),
        ("bullet",  "Filtered — neutral, small quality bonus across the board"),
    ],
    "Tea Making": [
        ("header",  "Tea Making"),
        ("body",    "Wild tea bushes grow in tropical, jungle, alpine, rolling hills,"),
        ("body",    "and tundra biomes. Each biome yields a distinct cultivar. You"),
        ("body",    "can also plant tea seeds on farmland for a reliable supply."),
        ("gap",),
        ("section", "BIOME → CULTIVAR"),
        ("bullet",  "Tropical        →  Assam  (bold, astringent)"),
        ("bullet",  "Jungle          →  Yunnan  (earthy, complex)"),
        ("bullet",  "Alpine Mountain →  Darjeeling  (floral, bright)"),
        ("bullet",  "Rolling Hills   →  Ceylon  (balanced)"),
        ("bullet",  "Tundra          →  High Mountain Oolong  (delicate, floral)"),
        ("gap",),
        ("section", "STEP 1 — Withering Rack"),
        ("body",    "Place a Withering Rack block and press E to open it."),
        ("body",    "Select a raw tea leaf, then choose a wither method:"),
        ("bullet",  "Sun Withered    — boosts sweetness, reduces vegetal notes"),
        ("bullet",  "Shade Withered  — lifts floral character"),
        ("bullet",  "Indoor Withered — reduces vegetal sharpness, builds complexity"),
        ("gap",),
        ("section", "STEP 2 — Oxidation Station  (Mini-game)"),
        ("body",    "Place an Oxidation Station block and press E to open it."),
        ("body",    "Select a withered leaf to begin oxidation."),
        ("gap",),
        ("body",    "The oxidation bar rises automatically. Hold SPACE to slow it."),
        ("body",    "Press ENTER or click LOCK when the bar reaches your target zone."),
        ("body",    "The zone the bar is in when you stop determines the tea type:"),
        ("bullet",  "0–20%   →  Green Tea   (tranquility buff — incoming damage -30%)"),
        ("bullet",  "20–75%  →  Oolong      (harmony buff — farm yield +25%)"),
        ("bullet",  "75–95%  →  Black Tea   (alertness buff — discovery XP +30%)"),
        ("bullet",  "95–100% →  Pu-erh      (longevity buff — hunger drain -55%)"),
        ("gap",),
        ("body",    "Quality is highest when you stop near the centre of the zone."),
        ("gap",),
        ("section", "STEP 3 — Tea Cellar  (Brew, Blend, Age)"),
        ("body",    "Place a Tea Cellar block and press E to open it."),
        ("body",    "Three tabs are available:"),
        ("gap",),
        ("body",    "Brew tab — select an oxidized leaf to brew into a tea item."),
        ("body",    "Higher steep quality produces fine or aged tier teas."),
        ("gap",),
        ("body",    "Blend tab — add herbal ingredients (ginger, chamomile) from"),
        ("body",    "your inventory to enrich the tea's flavor profile."),
        ("gap",),
        ("body",    "Age tab — Pu-erh only. Choose Short (3 mo), Medium (1 yr),"),
        ("body",    "or Long (3 yr) aging. Aging deepens earthiness and upgrades"),
        ("body",    "the output to fine or aged tier."),
        ("gap",),
        ("section", "RESEARCH — Tea Cultivation  (column 9)"),
        ("bullet",  "Tea Cultivation   — unlocks Withering Rack crafting"),
        ("bullet",  "Processing Arts   — unlocks Oxidation Station crafting"),
        ("bullet",  "Blending          — unlocks herbal additions in Tea Cellar"),
        ("bullet",  "Tea Ceremony      — unlocks Tea Cellar + fine/aged quality tier"),
    ],
    "Herbalism": [
        ("header",  "Herbalism & Alchemy"),
        ("body",    "Brew potions and elixirs from dried herbs, pressed wildflowers,"),
        ("body",    "and cave mushrooms. Recipes are discovered by experimenting with"),
        ("body",    "ingredient combinations in the Alchemical Kiln."),
        ("gap",),
        ("section", "GATHERING INGREDIENTS"),
        ("body",    "Mine cave mushrooms to collect cave_mushroom or rare_mushroom"),
        ("body",    "items. Press wildflowers and dry crop drops at the Drying Rack."),
        ("gap",),
        ("section", "STEP 1 — Drying Rack"),
        ("body",    "Place a Drying Rack block and press E to open it."),
        ("gap",),
        ("body",    "Left panel — dry inventory items:"),
        ("bullet",  "Mushroom / Cave Mushroom  →  Dried Mushroom"),
        ("bullet",  "Rare Mushroom             →  Rare Dried Mushroom"),
        ("bullet",  "Ginger                    →  Dried Ginger"),
        ("bullet",  "Garlic                    →  Dried Garlic"),
        ("gap",),
        ("body",    "Right panel — press wildflowers from your collection:"),
        ("bullet",  "Common / Uncommon wildflower  →  Pressed Flower"),
        ("bullet",  "Rare / Epic / Legendary       →  Pressed Rare Flower"),
        ("gap",),
        ("section", "STEP 2 — Alchemical Kiln  (Recipe Discovery)"),
        ("body",    "Place an Alchemical Kiln block and press E to open it."),
        ("body",    "Fill the 4 ingredient slots with dried/pressed ingredients,"),
        ("body",    "then click BREW."),
        ("gap",),
        ("body",    "If your combination matches a known recipe, you receive that"),
        ("body",    "potion. If not, you receive a Mystery Flask. Discovered recipes"),
        ("body",    "are saved permanently and shown in the recipe list on the right."),
        ("gap",),
        ("body",    "Basic potion recipes (examples):"),
        ("bullet",  "Dried Mushroom ×2 + Pressed Flower ×1        →  Health Potion"),
        ("bullet",  "Dried Ginger ×2 + Pressed Flower ×1          →  Speed Potion"),
        ("bullet",  "Dried Mushroom + Dried Ginger + Crystal Shard →  Mining Potion"),
        ("bullet",  "Rare Dried Mush + Pressed Rare Flower + Garlic→  Luck Potion"),
        ("body",    "Fine tier potions require rarer ingredients. Experiment!"),
        ("gap",),
        ("section", "STEP 3 — Resonance Chamber  (Elixirs)"),
        ("body",    "Place a Resonance Chamber block and press E to open it."),
        ("body",    "Uses 3 ingredient slots. All elixir recipes require Ruby."),
        ("body",    "Requires Resonance Mastery research to use."),
        ("gap",),
        ("body",    "Elixirs are stronger and longer-lasting than potions:"),
        ("bullet",  "Healing Elixir   — restores 60 HP instantly"),
        ("bullet",  "Swiftness Elixir — move speed +50% for 120s"),
        ("bullet",  "Mining Elixir    — mining speed +40%, +2 pick power for 180s"),
        ("bullet",  "Fortune Elixir   — rare drop chance +70% for 180s"),
        ("bullet",  "Fortitude Elixir — max health +40 for 180s"),
        ("gap",),
        ("section", "RESEARCH — Herbalism  (column 10)"),
        ("bullet",  "Herbalism Basics   — unlocks Drying Rack crafting"),
        ("bullet",  "Tincture Crafting  — unlocks basic potions in the Kiln"),
        ("bullet",  "Alchemy            — unlocks fine-tier potions"),
        ("bullet",  "Resonance Mastery  — unlocks Resonance Chamber elixirs"),
    ],
    "Textile Arts": [
        ("header",  "Textile & Fiber Arts"),
        ("body",    "Spin raw fiber into thread, dye it with wildflower pigments,"),
        ("body",    "then weave it into rugs, tapestries, and garments. Garments"),
        ("body",    "equip to worn slots and provide passive stat bonuses."),
        ("gap",),
        ("section", "FIBER SOURCES"),
        ("bullet",  "Wool      — shear Sheep with Shears (regrows after 30s)"),
        ("bullet",  "Flax      — harvest mature Flax plants (temperate, rolling hills, steppe biomes)"),
        ("bullet",  "Blend     — combine one Wool + one Flax Fiber at the Spinning Wheel"),
        ("gap",),
        ("section", "STEP 1 — Spinning Wheel"),
        ("body",    "Place a Spinning Wheel block and press E to open it."),
        ("body",    "Select a fiber type from your inventory."),
        ("gap",),
        ("body",    "Mini-game: Hold SPACE to raise the tension bar. Keep it"),
        ("body",    "in the green zone for the full 20 seconds. Staying in the"),
        ("body",    "zone builds quality; drifting outside wastes time."),
        ("body",    "On completion, a Thread textile is added to your collection."),
        ("gap",),
        ("section", "STEP 2 — Dye Vat  (optional)"),
        ("body",    "Place a Dye Vat block and press E to open it."),
        ("gap",),
        ("body",    "Extract tab — select a wildflower from your collection to"),
        ("body",    "extract dye. The flower is consumed; you receive a Dye Extract"),
        ("body",    "item. Flower color maps to one of 9 dye families:"),
        ("bullet",  "Golden  Crimson  Rose  Cobalt  Violet  Verdant  Amber  Ivory  Natural"),
        ("gap",),
        ("body",    "Dye tab — select a Thread textile and a Dye Extract from your"),
        ("body",    "inventory. Click Apply Dye. The thread is now dyed and ready"),
        ("body",    "to weave. Dyeing boosts luster slightly."),
        ("gap",),
        ("section", "STEP 3 — Loom  (Weaving Mini-game)"),
        ("body",    "Place a Loom block and press E to open it."),
        ("body",    "Select a thread, then choose:"),
        ("bullet",  "Texture — Plain / Twill / Herringbone / Diamond  (complexity adds pattern quality)"),
        ("bullet",  "Output  — Cloth / Rug / Tapestry / Hat / Vest / Boots"),
        ("gap",),
        ("body",    "Mini-game: A 5×4 grid of cells appears. Cells light up one"),
        ("body",    "at a time. Click each highlighted cell before it dims."),
        ("body",    "Faster clicks score higher pattern quality."),
        ("gap",),
        ("body",    "On completion the textile is added to your collection and"),
        ("body",    "a matching item (rug / tapestry / garment) is placed in"),
        ("body",    "your inventory."),
        ("gap",),
        ("section", "GARMENTS & WORN SLOTS"),
        ("body",    "Press T to open the Wardrobe panel. Equip garments to slots:"),
        ("bullet",  "Head (Hat)   — Focus   : mining speed up to +25% (scales with quality)"),
        ("bullet",  "Chest (Vest) — Resilience : damage taken up to -20%"),
        ("bullet",  "Feet (Boots) — Swiftness  : move speed up to +20%"),
        ("gap",),
        ("body",    "Click an equipped slot to unequip; click a garment in the"),
        ("body",    "inventory list to equip it. Only one garment per slot."),
        ("gap",),
        ("section", "RUGS & TAPESTRIES"),
        ("body",    "Rugs are placeable floor blocks; tapestries are wall blocks."),
        ("body",    "Both come in 9 dye variants matching your chosen color family."),
        ("body",    "Place them from your hotbar to decorate your home interior."),
        ("gap",),
        ("section", "RESEARCH — Textile Arts  (column 11)"),
        ("bullet",  "Fiber Arts Basics  — unlocks Spinning Wheel crafting"),
        ("bullet",  "Natural Dyeing     — unlocks Dye Vat crafting"),
        ("bullet",  "Loom Mastery       — unlocks Loom crafting"),
        ("bullet",  "Master Weaver      — unlocks diamond texture and tapestry output"),
    ],
    "Horse Taming": [
        ("header",  "Horse Taming"),
        ("body",    "Wild horses spawn in herds across grassland and prairie biomes."),
        ("body",    "Tame them with food, break them with a minigame, then ride."),
        ("gap",),
        ("section", "STEP 1 — Feed to Tame"),
        ("body",    "Equip a food item and right-click a wild horse to offer it."),
        ("body",    "Each feed raises tame progress toward the threshold."),
        ("bullet",  "Apple, Carrot, Wheat  →  +1 progress each feed"),
        ("bullet",  "Sugar Lump            →  +2 progress per feed"),
        ("bullet",  "Horse Brush           →  +2 progress, consumes the brush"),
        ("gap",),
        ("body",    "Taming threshold depends on temperament:"),
        ("bullet",  "Calm      →  5 feeds required   (easiest)"),
        ("bullet",  "Spirited  →  9 feeds required"),
        ("bullet",  "Wild      →  14 feeds required  (hardest)"),
        ("gap",),
        ("section", "STEP 2 — Breaking Minigame"),
        ("body",    "Equip a Saddle and right-click a tamed horse to trigger"),
        ("body",    "the breaking minigame. The horse bucks left and right."),
        ("gap",),
        ("body",    "Hold A / D (or arrow keys) to stay balanced on the horse."),
        ("body",    "Keep the balance meter centred for the required duration."),
        ("body",    "Falling off (balance reaches 0 or 100) counts as a failure."),
        ("gap",),
        ("body",    "Break time and buck frequency scale with temperament:"),
        ("bullet",  "Calm      →  short duration, slow bucks"),
        ("bullet",  "Spirited  →  medium duration, frequent bucks"),
        ("bullet",  "Wild      →  long duration, fast unpredictable bucks"),
        ("gap",),
        ("section", "STEP 3 — Riding"),
        ("body",    "Once broken, right-click the horse to mount it."),
        ("bullet",  "SPACE        — sprint  (drains stamina)"),
        ("bullet",  "Arrow keys   — move while mounted"),
        ("bullet",  "E            — dismount"),
        ("gap",),
        ("body",    "Stamina regenerates when not sprinting. Horses with higher"),
        ("body",    "speed_rating move faster; higher stamina_max sprint longer."),
        ("gap",),
        ("section", "BREEDING"),
        ("body",    "Place a Stable block near two tamed, broken horses."),
        ("body",    "Both must be off cooldown. Open the Animals panel (E near"),
        ("body",    "the Stable) and select a pair to breed. The foal inherits"),
        ("body",    "averaged traits from both parents with slight variation."),
        ("gap",),
        ("section", "HORSESHOES"),
        ("body",    "Craft Iron Horseshoes and apply them to a tamed horse"),
        ("body",    "to permanently boost its speed rating."),
    ],
    "Animal Taming": [
        ("header",  "Animal Taming"),
        ("body",    "Wild Sheep, Goats, Cows, and Chickens roam the world."),
        ("body",    "Tame them with food to unlock harvesting and breeding."),
        ("gap",),
        ("section", "HOW TO TAME"),
        ("body",    "Equip a preferred food item in your hotbar, then"),
        ("body",    "right-click a wild animal to offer it. Repeat until"),
        ("body",    "the animal is tamed (3 feeds for most animals;"),
        ("body",    "albino mutation reduces this to 2)."),
        ("gap",),
        ("section", "ANIMALS, FOODS & YIELDS"),
        ("bullet",  "Sheep   — wheat / carrot   →  wool (Shears), milk (Bucket)"),
        ("bullet",  "Goat    — wheat / carrot   →  goat milk (Bucket)"),
        ("bullet",  "Cow     — wheat / apple    →  cow milk (Bucket)"),
        ("bullet",  "Chicken — corn / pea       →  eggs (empty hand)"),
        ("gap",),
        ("section", "HARVESTING"),
        ("body",    "Equip the correct tool, stand near a tamed animal,"),
        ("body",    "and hold right-click to harvest. Each resource has"),
        ("body",    "a refill timer before it can be harvested again."),
        ("bullet",  "Wool     — use Shears; regrows after ~30 s"),
        ("bullet",  "Milk     — use Bucket; refills after ~25 s"),
        ("bullet",  "Eggs     — no tool needed; refills after ~30 s"),
        ("gap",),
        ("body",    "Golden mutation animals occasionally drop bonus golden"),
        ("body",    "variants (golden wool, golden milk, golden egg)."),
        ("gap",),
        ("section", "BREEDING"),
        ("body",    "Two tamed animals of the same type that are near each"),
        ("body",    "other will breed automatically once their cooldowns reset."),
        ("body",    "Offspring inherit averaged traits from both parents,"),
        ("body",    "with slight variation. Selectively breed high-productivity"),
        ("body",    "animals to improve your herd over time."),
        ("gap",),
        ("body",    "Miniature mutation offspring have a shorter breed cooldown."),
        ("body",    "Sheep with the twin gene have a 60% chance to birth twins."),
    ],
    "Farming": [
        ("header",  "Farming"),
        ("body",    "Grow crops by planting seeds on prepared soil."),
        ("gap",),
        ("section", "PLANTING"),
        ("body",    "Equip seeds in your hotbar and right-click on tilled"),
        ("body",    "soil to plant them. Crops grow automatically over time"),
        ("body",    "and must be harvested once fully grown."),
        ("gap",),
        ("section", "SOIL"),
        ("body",    "Use a hoe on dirt blocks to create tilled soil. Crops"),
        ("body",    "planted on fertile soil grow faster."),
        ("gap",),
        ("section", "FARM BOT"),
        ("body",    "Farm Bots automate planting and harvesting. Place one"),
        ("body",    "nearby and press E to configure seeds and fuel."),
    ],
    "Crafting": [
        ("header",  "Crafting"),
        ("body",    "Open the crafting panel with C. Place items into the"),
        ("body",    "3x3 grid and a matching recipe will appear on the right."),
        ("gap",),
        ("section", "EQUIPMENT"),
        ("body",    "Specialized blocks unlock additional recipes:"),
        ("bullet",  "Bakery            — baked goods and breads"),
        ("bullet",  "Wok               — stir-fry dishes"),
        ("bullet",  "Desert Forge      — metal tools and equipment"),
        ("bullet",  "Artisan Bench     — advanced crafted items"),
        ("bullet",  "Copper Still      — distilled spirits"),
        ("bullet",  "Barrel Room       — aged spirits"),
        ("bullet",  "Bottling Station  — bottled & blended spirits"),
        ("gap",),
        ("section", "RESEARCH LOCKS"),
        ("body",    "Some recipes are locked until researched. Open the"),
        ("body",    "Research tree with R to unlock new crafting options."),
    ],
    "Mining": [
        ("header",  "Mining"),
        ("body",    "Mine blocks with a pickaxe. Deeper layers contain"),
        ("body",    "rarer rocks, gems, and fossils."),
        ("gap",),
        ("section", "DEPTH"),
        ("body",    "The depth indicator in the HUD shows your current"),
        ("body",    "underground level. The deeper you go, the rarer the"),
        ("body",    "materials you will find."),
        ("gap",),
        ("section", "PICKAXES"),
        ("body",    "Better pickaxes mine faster and can break harder blocks."),
        ("body",    "Upgrade your tools at the Desert Forge."),
        ("gap",),
        ("section", "BACKHOE"),
        ("body",    "The Backhoe machine excavates large areas automatically."),
        ("body",    "Fuel it with oil barrels. Press E near it to mount or"),
        ("body",    "manage fuel. Use arrow keys to move the arm while riding."),
    ],
    "Collecting": [
        ("header",  "Collecting"),
        ("body",    "Open your collection panel with G. Items you pick up"),
        ("body",    "are automatically catalogued by category."),
        ("gap",),
        ("section", "CATEGORIES"),
        ("body",    "The collection tracks: rocks, wildflowers, fossils,"),
        ("body",    "gems, mushrooms, coffee, wine, and spirits."),
        ("body",    "Use the filter buttons at the top to sort by type."),
        ("gap",),
        ("section", "ENCYCLOPEDIA"),
        ("body",    "The Encyclopedia tab lists all known species and types"),
        ("body",    "in the world, including ones you haven't found yet."),
        ("body",    "Click an entry to see details and rarity information."),
        ("gap",),
        ("section", "AWARDS"),
        ("body",    "Complete collection milestones to earn awards and"),
        ("body",    "unlock special bonuses. Check the Awards tab in the"),
        ("body",    "collection panel to see your progress."),
    ],
    "Research": [
        ("header",  "Research"),
        ("body",    "Open the research tree with R. Spend research points"),
        ("body",    "to unlock nodes and gain new abilities and recipes."),
        ("gap",),
        ("section", "GAINING POINTS"),
        ("body",    "Research points are earned by collecting items, mining"),
        ("body",    "rare materials, and completing quests from NPCs."),
        ("gap",),
        ("section", "UNLOCKS"),
        ("body",    "Research unlocks crafting recipes, equipment upgrades,"),
        ("body",    "and world features. Plan your tree carefully — some"),
        ("body",    "advanced nodes require earlier nodes to be unlocked first."),
        ("gap",),
        ("section", "COLUMNS"),
        ("body",    "The tree is organized in columns by theme:"),
        ("bullet",  "Column 1  — Gathering & Tools"),
        ("bullet",  "Column 2  — Food & Cooking"),
        ("bullet",  "Column 3  — Mining & Geology"),
        ("bullet",  "Column 4  — Coffee & Wine"),
        ("bullet",  "Column 5  — Automation"),
        ("bullet",  "Column 6  — Distilling"),
    ],

    "Sculpting": [
        ("header",  "Sculpting"),
        ("body",    "Sculpting lets you carve decorative background blocks from"),
        ("body",    "stone minerals. Sculptures are placed on the wall layer and"),
        ("body",    "can be 1–4 blocks tall."),
        ("gap",),
        ("section", "GETTING STARTED"),
        ("bullet",  "Unlock Stone Carving in the Masonry Arts research column"),
        ("bullet",  "Craft a Stone Chisel: 2 Stone Chips + 1 Lumber"),
        ("bullet",  "Craft a Sculptor's Bench: Stone Chips + Chisel + Iron Ingot"),
        ("bullet",  "Mine minerals and bring them to the bench"),
        ("gap",),
        ("section", "MINERALS"),
        ("body",    "Common stones can be mined anywhere underground:"),
        ("bullet",  "Limestone Chip  —  depth 15–60  (sedimentary biomes)"),
        ("bullet",  "Granite Slab    —  depth 60–120"),
        ("bullet",  "Basalt Chunk    —  depth 120–180"),
        ("bullet",  "Magmatic Stone  —  depth 180+"),
        ("gap",),
        ("body",    "Rare stones worth seeking out:"),
        ("bullet",  "Marble Chunk    —  depth 25–80   (sedimentary, rare)"),
        ("bullet",  "Alabaster Chunk —  depth 15–55   (sedimentary, rare)"),
        ("bullet",  "Verdite Slab    —  depth 60–140  (igneous, rare)"),
        ("bullet",  "Onyx Slab       —  depth 130+    (igneous, very rare)"),
        ("gap",),
        ("section", "THE MINI-GAME"),
        ("body",    "Step 1  —  Pick a mineral and height (1–4 blocks tall)"),
        ("body",    "Step 2  —  Choose a template or start blank (Custom)"),
        ("body",    "Step 3  —  Carve the grid:"),
        ("bullet",  "Left-drag   carve stone away"),
        ("bullet",  "Right-drag  restore stone"),
        ("bullet",  "Z           undo last stroke"),
        ("bullet",  "S           toggle mirror symmetry"),
        ("bullet",  "ENTER       move to preview"),
        ("gap",),
        ("section", "TEMPLATES"),
        ("body",    "39 templates available in categories:"),
        ("bullet",  "Classic  — Pillar, Column, Arch, Obelisk, Monolith…"),
        ("bullet",  "Shapes   — Pyramid, Diamond, Cross, Hourglass, Frame…"),
        ("bullet",  "Organic  — Tree, Mushroom, Flame, Wave, Vase…"),
        ("bullet",  "Renaissance — Corinthian, Bust, Baluster, Tondo…"),
        ("bullet",  "Chinese     — Pagoda, Lantern, Moon Gate, Foo Dog…"),
        ("gap",),
        ("section", "PLACING & REMOVING"),
        ("body",    "Hold SHIFT and left-click a background wall tile to place."),
        ("body",    "The sculpture occupies 1–4 background tiles vertically."),
        ("body",    "Mine the bottom (root) block to remove the whole sculpture."),
        ("gap",),
        ("section", "RESEARCH UPGRADES"),
        ("bullet",  "Stone Carving    — unlocks Sculptor's Bench"),
        ("bullet",  "Fine Chiseling   — higher grid resolution"),
        ("bullet",  "Master Sculptor  — unlocks Effigy template"),
    ],

    "Pottery": [
        ("header",  "Pottery & Ceramics"),
        ("body",    "Shape clay into functional and decorative pieces. Four clay"),
        ("body",    "types produce distinct textures and firing characteristics."),
        ("gap",),
        ("section", "GETTING STARTED"),
        ("bullet",  "Unlock Clay Working in the Ceramics research column"),
        ("bullet",  "Mine Clay Deposits underground in wetland, river, or swamp biomes"),
        ("bullet",  "Craft a Pottery Wheel (Clay + Lumber) and place it"),
        ("bullet",  "Unlock Kiln Mastery, then craft a Pottery Kiln (Clay + Coal)"),
        ("gap",),
        ("section", "CLAY TYPES & WHERE TO FIND THEM"),
        ("bullet",  "Wetland  —  Red Clay (earthenware): dense, earthy, iron-rich"),
        ("bullet",  "Tropical —  White Kaolin (porcelain): fine, smooth, excellent glaze"),
        ("bullet",  "Temperate — Grey Stoneware: durable, thick-walled, reliable"),
        ("bullet",  "River    —  Blue Clay (slipware): smooth, high glaze affinity"),
        ("gap",),
        ("section", "POTTERY WHEEL — SHAPING"),
        ("body",    "Load 3–8 clay chunks. More clay = larger starting profile."),
        ("body",    "The profile editor shows 12 rows (top → bottom of the piece):"),
        ("bullet",  "Click + on a row  →  widen that section (costs 1 clay)"),
        ("bullet",  "Click - on a row  →  narrow that section (refunds 1 clay)"),
        ("bullet",  "Drag on silhouette  →  adjust width at that height"),
        ("bullet",  "Z                   →  undo last change"),
        ("bullet",  "ENTER / SHAPE btn   →  proceed to confirm"),
        ("body",    "The detected shape (Pot, Amphora, Jar, Jug, Vase) determines"),
        ("body",    "which functional item is produced after firing."),
        ("gap",),
        ("section", "SHAPES & THEIR EFFECTS"),
        ("bullet",  "Pot      —  Clay Cooking Pot: food stations yield +1 serving"),
        ("bullet",  "Amphora  —  Wine Amphora: wine complexity +0.15 per bottle"),
        ("bullet",  "Jar      —  Herb Storage Jar: dried herbs last 50% longer"),
        ("bullet",  "Jug      —  Water Jug: farm tiles count as irrigated"),
        ("bullet",  "Vase     —  Pottery Vase: decorative collectible"),
        ("gap",),
        ("section", "POTTERY KILN — FIRING"),
        ("body",    "Select a formed piece. Hold SPACE (or click HEAT) to raise"),
        ("body",    "temperature. Release to let it cool. The firing lasts 35 seconds."),
        ("gap",),
        ("body",    "Temperature zones determine firing level:"),
        ("bullet",  "35–55%   →  Intact tier   (base functional item)"),
        ("bullet",  "55–72%   →  Fine tier      (longer buff duration)"),
        ("bullet",  "72–82%   →  Masterwork tier (maximum duration)"),
        ("bullet",  "Above 85%  →  Thermal shock accumulates → risk of cracking"),
        ("gap",),
        ("body",    "Events during firing (at 8s, 18s, 28s) signal key phases."),
        ("body",    "A cracked piece is worthless; careful temperature control matters."),
        ("gap",),
        ("section", "GLAZING (requires Glaze Arts research)"),
        ("body",    "Use the Glaze tab in the Pottery Kiln. Select a fired piece"),
        ("body",    "and a gem dust type (2 dust required):"),
        ("bullet",  "Ruby Dust      →  Ruby Glaze   (deep red coating)"),
        ("bullet",  "Emerald Dust   →  Emerald Glaze (forest green)"),
        ("bullet",  "Sapphire Dust  →  Sapphire Glaze (ocean blue)"),
        ("bullet",  "Amethyst Dust  →  Amethyst Glaze (violet)"),
        ("bullet",  "Topaz Dust     →  Topaz Glaze   (amber)"),
        ("body",    "Glazing upgrades the piece one tier (intact → fine → masterwork)"),
        ("body",    "and with Glaze Arts research extends buff durations by 50%."),
        ("gap",),
        ("body",    "Gem dust is crafted at the Pottery Kiln from gem items"),
        ("body",    "(1 gem → 3 dust). Unlocked by the Glaze Arts research node."),
        ("gap",),
        ("section", "USING POTTERY ITEMS"),
        ("body",    "Select a functional pottery item in your hotbar and press E"),
        ("body",    "to activate its buff. Buffs last 120–600 seconds depending"),
        ("body",    "on tier and research. Pottery buffs stack with food, coffee,"),
        ("body",    "wine, and herb buffs."),
        ("gap",),
        ("section", "COLLECTING & CODEX"),
        ("body",    "The Pottery Codex tracks 4 clay types × 3 firing levels = 12"),
        ("body",    "discoverable combinations. Access it via the Encyclopedia"),
        ("body",    "tab (G → ENCYCLOPEDIA → POTTERY)."),
        ("gap",),
        ("section", "RESEARCH UPGRADES"),
        ("bullet",  "Clay Working  — unlocks Pottery Wheel"),
        ("bullet",  "Kiln Mastery  — unlocks Pottery Kiln, +15% firing quality"),
        ("bullet",  "Glaze Arts    — unlocks glazing tab and gem dust recipes,"),
        ("body",    "                +50% pottery buff duration"),
    ],

    "Salt": [
        ("header",  "Salt Harvesting & Processing"),
        ("body",    "Mine salt deposits underground, evaporate the crystals to dry"),
        ("body",    "them, then grind them into one of three grades — each granting"),
        ("body",    "a different gameplay buff when consumed."),
        ("gap",),
        ("section", "GETTING STARTED"),
        ("bullet",  "Unlock Salt Basics in the research tree"),
        ("bullet",  "Craft an Evaporation Pan (Iron + Stone) and place it"),
        ("bullet",  "Craft a Salt Grinder (Stone + Iron + Lumber) and place it"),
        ("bullet",  "Mine Salt Deposits found underground in sedimentary,"),
        ("body",    "  arid steppe, and igneous biomes (depth < 60)"),
        ("gap",),
        ("section", "BIOMES & SALT CHARACTER"),
        ("bullet",  "Desert / Arid Steppe  —  High purity, low moisture, solar variety"),
        ("bullet",  "Alpine                —  Very high purity, brine variety"),
        ("bullet",  "Coastal / Tropical    —  Medium purity, good salinity, solar"),
        ("bullet",  "Volcanic              —  High mineral content, volcanic variety"),
        ("bullet",  "Wetland / Boreal      —  Low purity, high moisture, brine variety"),
        ("bullet",  "Sedimentary           —  Balanced, medium grain, brine variety"),
        ("bullet",  "Temperate             —  Mild all-around, solar variety"),
        ("gap",),
        ("section", "STEP 1 — EVAPORATION PAN"),
        ("body",    "Select a raw crystal and choose an evaporation method:"),
        ("bullet",  "Solar Drying     —  gentle, boosts purity and salinity"),
        ("bullet",  "Brine Pool       —  moderate, raises mineral and moisture"),
        ("bullet",  "Volcanic Vent    —  intense, high variance, reduces moisture"),
        ("gap",),
        ("body",    "The mini-game runs for 30 seconds. Hold SPACE to raise"),
        ("body",    "temperature; release to let it fall. Keep it in the sweet"),
        ("body",    "zone (35–65%) as long as possible."),
        ("gap",),
        ("bullet",  "Sweet zone (35–65%)  →  green — time here drives quality"),
        ("bullet",  "Danger zone (>85%)   →  red   — overheat penalty every 1.5s"),
        ("bullet",  "ENTER                →  stop early and harvest"),
        ("gap",),
        ("body",    "Two milestone events fire during evaporation:"),
        ("bullet",  "Nucleation Stage  (10s)  —  crystal structure forming"),
        ("bullet",  "Harvest Window    (22s)  —  peak quality available"),
        ("gap",),
        ("body",    "Score = time in sweet zone ÷ total time elapsed."),
        ("bullet",  "Score < 0.40   →  base tier"),
        ("bullet",  "Score 0.40–0.70 →  fine tier   (+25% buff duration)"),
        ("bullet",  "Score ≥ 0.70   →  reserve tier (+100% buff duration)"),
        ("gap",),
        ("section", "STEP 2 — SALT GRINDER"),
        ("body",    "Select a dried crystal and choose a refine grade:"),
        ("gap",),
        ("bullet",  "Coarse Salt    —  any crystal; vitality buff"),
        ("body",    "               →  Mining speed +15%  (60 / 90 / 120s)"),
        ("gap",),
        ("bullet",  "Fine Salt      —  any crystal; preservation buff"),
        ("body",    "               →  Hunger restore +25%  (90 / 120 / 150s)"),
        ("gap",),
        ("bullet",  "Fleur de Sel   —  purity ≥ 0.65 AND moisture ≤ 0.35"),
        ("body",    "               →  Refinement buff: crafting quality +20%"),
        ("body",    "               →  (75 / 105 / 135s per tier)"),
        ("body",    "  If the crystal fails these thresholds it demotes to Fine Salt."),
        ("body",    "  A red border on the button warns you before you commit."),
        ("gap",),
        ("section", "SALT IN COOKING"),
        ("body",    "Salt grades are also ingredients in cooked dishes:"),
        ("bullet",  "Salted Bread      —  Bakery: wheat ×3 + fine salt"),
        ("body",    "                    preservation buff 60s"),
        ("bullet",  "Artisan Loaf      —  Bakery: wheat ×3 + fleur de sel"),
        ("body",    "                    refinement buff 60s"),
        ("bullet",  "Salt-Cured Beef   —  Clay Pot: cooked beef + coarse salt ×2"),
        ("body",    "                    vitality buff 90s"),
        ("bullet",  "Salt-Cured Mutton —  BBQ Grill: raw mutton + coarse salt ×2"),
        ("body",    "                    vitality buff 90s"),
        ("bullet",  "Salted Lentil Soup — Clay Pot: lentil ×3 + onion + tomato"),
        ("body",    "                    + fine salt  →  preservation buff 90s"),
        ("gap",),
        ("section", "BUFFS"),
        ("bullet",  "Vitality      —  Mining speed +15%"),
        ("bullet",  "Preservation  —  Hunger restore +25% when eating"),
        ("bullet",  "Refinement    —  Crafting quality +20%"),
        ("body",    "Only one salt buff can be active at a time. Eating a second"),
        ("body",    "salt item replaces the current buff with the new one."),
        ("gap",),
        ("section", "COLLECTING & CODEX"),
        ("body",    "The Salt Codex tracks 10 biomes × 3 grades = 30 combinations."),
        ("body",    "A combination is discovered the first time you finish grinding"),
        ("body",    "a crystal from that biome into that grade."),
        ("body",    "Access via G → ENCYCLOPEDIA → SALT."),
    ],
}


class HelpMixin:

    def _draw_help(self):
        overlay = pygame.Surface((SCREEN_W, SCREEN_H), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 210))
        self.screen.blit(overlay, (0, 0))

        panel = pygame.Rect(20, 20, SCREEN_W - 40, SCREEN_H - 40)
        pygame.draw.rect(self.screen, (18, 18, 28), panel)
        pygame.draw.rect(self.screen, (80, 80, 130), panel, 2)

        title_surf = self.font.render("HELP", True, (200, 200, 255))
        self.screen.blit(title_surf, (panel.centerx - title_surf.get_width() // 2, panel.y + 8))
        hint = self.small.render("ESC to close", True, (100, 100, 150))
        self.screen.blit(hint, (panel.right - hint.get_width() - 10, panel.y + 10))

        CONTENT_Y = panel.y + 34
        LEFT_W = 190

        # Left topic panel
        left_rect = pygame.Rect(panel.x + 8, CONTENT_Y, LEFT_W, panel.bottom - CONTENT_Y - 8)
        pygame.draw.rect(self.screen, (12, 12, 22), left_rect)
        pygame.draw.rect(self.screen, (50, 50, 80), left_rect, 1)

        self._help_topic_rects.clear()
        ty = left_rect.y + 10
        for topic in _TOPICS:
            btn = pygame.Rect(left_rect.x + 4, ty, left_rect.width - 8, 28)
            self._help_topic_rects[topic] = btn
            selected = (self._help_topic == topic)
            if selected:
                pygame.draw.rect(self.screen, (40, 40, 80), btn)
                pygame.draw.rect(self.screen, (100, 100, 190), btn, 1)
            label_col = (220, 220, 255) if selected else (150, 150, 190)
            label = self.small.render(topic, True, label_col)
            self.screen.blit(label, (btn.x + 10, btn.y + 7))
            ty += 34

        # Right content panel
        right_x = panel.x + LEFT_W + 16
        right_w = panel.right - right_x - 8
        right_rect = pygame.Rect(right_x, CONTENT_Y, right_w, panel.bottom - CONTENT_Y - 8)
        pygame.draw.rect(self.screen, (12, 12, 22), right_rect)
        pygame.draw.rect(self.screen, (50, 50, 80), right_rect, 1)

        content = _CONTENT.get(self._help_topic, [])
        LINE_H = 17

        # Measure total content height
        total_h = 0
        for entry in content:
            if entry[0] == "header":
                total_h += 28
            elif entry[0] == "section":
                total_h += 24
            elif entry[0] == "gap":
                total_h += 10
            else:
                total_h += LINE_H

        visible_h = right_rect.height - 16
        self._help_max_scroll = max(0, total_h - visible_h)
        self._help_scroll = max(0, min(self._help_max_scroll, self._help_scroll))

        SB_W = 10
        content_w = right_w - SB_W - 4 if self._help_max_scroll > 0 else right_w - 4

        clip = pygame.Rect(right_rect.x + 1, right_rect.y + 1, right_rect.width - 2, right_rect.height - 2)
        old_clip = self.screen.get_clip()
        self.screen.set_clip(clip)

        cx = right_rect.x + 12
        y = right_rect.y + 8 - self._help_scroll

        for entry in content:
            kind = entry[0]
            if kind == "header":
                surf = self.font.render(entry[1], True, (200, 200, 255))
                self.screen.blit(surf, (cx, y))
                y += 28
            elif kind == "section":
                surf = self.small.render(entry[1], True, (140, 200, 140))
                self.screen.blit(surf, (cx, y))
                pygame.draw.line(self.screen, (70, 110, 70),
                                 (cx, y + 15), (right_rect.x + content_w, y + 15), 1)
                y += 24
            elif kind == "bullet":
                surf = self.small.render("  •  " + entry[1], True, (185, 185, 210))
                self.screen.blit(surf, (cx + 8, y))
                y += LINE_H
            elif kind == "body":
                text = entry[1] if len(entry) > 1 else ""
                if text:
                    surf = self.small.render(text, True, (185, 185, 210))
                    self.screen.blit(surf, (cx, y))
                y += LINE_H
            elif kind == "gap":
                y += 10

        self.screen.set_clip(old_clip)

        # Scrollbar
        if self._help_max_scroll > 0:
            sb_x = right_rect.right - SB_W - 2
            sb_track_h = right_rect.height - 4
            thumb_h = max(20, int(sb_track_h * visible_h / max(total_h, 1)))
            thumb_y = right_rect.y + 2 + int(
                (sb_track_h - thumb_h) * self._help_scroll / self._help_max_scroll
            )
            pygame.draw.rect(self.screen, (30, 30, 50),
                             (sb_x, right_rect.y + 2, SB_W, sb_track_h))
            pygame.draw.rect(self.screen, (90, 90, 140),
                             (sb_x, thumb_y, SB_W, thumb_h))

    def handle_help_click(self, pos):
        for topic, rect in self._help_topic_rects.items():
            if rect.collidepoint(pos):
                self._help_topic = topic
                self._help_scroll = 0
                return
